[2025-03-07 13:49:52,426] [INFO] Starting node at localhost:30076 | index= 77 | f=1, k=4 | Role: Replica
[2025-03-07 13:49:55,102] [INFO] [30076] Received PRE-PREPARE: id:1741322995010, from:Leader(30000), delay:0.0000s, distance:162.75m (Euclidean)
[2025-03-07 13:49:55,105] [INFO] [30076] Broadcasting PREPARE for REQUEST 1741322995010
[2025-03-07 13:49:55,325] [INFO] [30076] Received PREPARE: id:1741322995010, from:30075, delay:0.0000s, distance:66.45m (Euclidean)
[2025-03-07 13:49:55,347] [INFO] [30076] Received PREPARE: id:1741322995010, from:30024, delay:0.0000s, distance:200.68m (Euclidean)
[2025-03-07 13:49:55,347] [INFO] [30076] Broadcasting COMMIT for REQUEST 1741322995010
[2025-03-07 13:49:55,596] [INFO] [30076] Received PREPARE: id:1741322995010, from:30054, delay:0.0001s, distance:186.18m (Euclidean)
[2025-03-07 13:49:55,614] [INFO] [30076] Received PREPARE: id:1741322995010, from:30009, delay:0.0000s, distance:249.67m (Euclidean)
[2025-03-07 13:49:55,623] [INFO] [30076] Received COMMIT: id:1741322995010, from:30075, delay:0.0000s, distance:66.45m (Euclidean)
[2025-03-07 13:49:55,646] [INFO] [30076] Received PREPARE: id:1741322995010, from:30079, delay:0.0000s, distance:118.47m (Euclidean)
[2025-03-07 13:49:55,763] [INFO] [30076] Received COMMIT: id:1741322995010, from:30079, delay:0.0000s, distance:118.47m (Euclidean)
[2025-03-07 13:49:55,763] [INFO] [LEADER 30076] Sending REPLY for REQUEST 1741322995010 to CLIENT
[2025-03-07 13:49:55,776] [INFO] [30076] Received PREPARE: id:1741322995010, from:30036, delay:0.0001s, distance:181.27m (Euclidean)
[2025-03-07 13:49:55,801] [INFO] [30076] Received COMMIT: id:1741322995010, from:30036, delay:0.0001s, distance:181.27m (Euclidean)
[2025-03-07 13:49:55,881] [INFO] [30076] Received PREPARE: id:1741322995010, from:30029, delay:0.0000s, distance:109.93m (Euclidean)
[2025-03-07 13:49:55,899] [INFO] [30076] Received COMMIT: id:1741322995010, from:30029, delay:0.0000s, distance:109.93m (Euclidean)
[2025-03-07 13:49:55,910] [INFO] [30076] Received PREPARE: id:1741322995010, from:30021, delay:0.0001s, distance:226.25m (Euclidean)
[2025-03-07 13:49:55,913] [INFO] [30076] Received COMMIT: id:1741322995010, from:30021, delay:0.0001s, distance:226.25m (Euclidean)
[2025-03-07 13:49:55,928] [INFO] [30076] Received COMMIT: id:1741322995010, from:30054, delay:0.0001s, distance:186.18m (Euclidean)
[2025-03-07 13:49:55,967] [INFO] [30076] Received COMMIT: id:1741322995010, from:30024, delay:0.0000s, distance:200.68m (Euclidean)
[2025-03-07 13:49:56,023] [INFO] [30076] Received PREPARE: id:1741322995010, from:30015, delay:0.0001s, distance:187.68m (Euclidean)
[2025-03-07 13:49:56,095] [INFO] [30076] Received PREPARE: id:1741322995010, from:30077, delay:0.0002s, distance:252.72m (Euclidean)
[2025-03-07 13:49:56,100] [INFO] [30076] Received COMMIT: id:1741322995010, from:30077, delay:0.0002s, distance:252.72m (Euclidean)
[2025-03-07 13:49:56,107] [INFO] [30076] Received PREPARE: id:1741322995010, from:30050, delay:0.0001s, distance:243.86m (Euclidean)
[2025-03-07 13:49:56,108] [INFO] [30076] Received COMMIT: id:1741322995010, from:30050, delay:0.0001s, distance:243.86m (Euclidean)
[2025-03-07 13:49:56,110] [INFO] [30076] Received PREPARE: id:1741322995010, from:30068, delay:0.0001s, distance:168.07m (Euclidean)
[2025-03-07 13:49:56,134] [INFO] [30076] Received COMMIT: id:1741322995010, from:30068, delay:0.0001s, distance:168.07m (Euclidean)
[2025-03-07 13:49:56,181] [INFO] [30076] Received PREPARE: id:1741322995010, from:30020, delay:0.0000s, distance:40.85m (Euclidean)
[2025-03-07 13:49:56,201] [INFO] [30076] Received COMMIT: id:1741322995010, from:30009, delay:0.0000s, distance:249.67m (Euclidean)
[2025-03-07 13:49:56,218] [INFO] [30076] Received PREPARE: id:1741322995010, from:30041, delay:0.0001s, distance:170.29m (Euclidean)
[2025-03-07 13:49:56,218] [INFO] [30076] Received COMMIT: id:1741322995010, from:30041, delay:0.0001s, distance:170.29m (Euclidean)
[2025-03-07 13:49:56,241] [INFO] [30076] Received COMMIT: id:1741322995010, from:30020, delay:0.0000s, distance:40.85m (Euclidean)
[2025-03-07 13:49:56,243] [INFO] [30076] Received PREPARE: id:1741322995010, from:30019, delay:0.0001s, distance:199.81m (Euclidean)
[2025-03-07 13:49:56,299] [INFO] [30076] Received PREPARE: id:1741322995010, from:30006, delay:0.0000s, distance:131.02m (Euclidean)
[2025-03-07 13:49:56,332] [INFO] [30076] Received PREPARE: id:1741322995010, from:30039, delay:0.0000s, distance:136.17m (Euclidean)
[2025-03-07 13:49:56,364] [INFO] [30076] Received PREPARE: id:1741322995010, from:30046, delay:0.0001s, distance:194.05m (Euclidean)
[2025-03-07 13:49:56,367] [INFO] [30076] Received PREPARE: id:1741322995010, from:30014, delay:0.0000s, distance:128.28m (Euclidean)
[2025-03-07 13:49:56,371] [INFO] [30076] Received COMMIT: id:1741322995010, from:30061, delay:0.0000s, distance:146.38m (Euclidean)
[2025-03-07 13:49:56,371] [INFO] [30076] Received PREPARE: id:1741322995010, from:30061, delay:0.0000s, distance:146.38m (Euclidean)
[2025-03-07 13:49:56,376] [INFO] [30076] Received COMMIT: id:1741322995010, from:30046, delay:0.0001s, distance:194.05m (Euclidean)
[2025-03-07 13:49:56,482] [INFO] [30076] Received COMMIT: id:1741322995010, from:30015, delay:0.0001s, distance:187.68m (Euclidean)
[2025-03-07 13:49:56,492] [INFO] [30076] Received PREPARE: id:1741322995010, from:30063, delay:0.0001s, distance:243.81m (Euclidean)
[2025-03-07 13:49:56,503] [INFO] [30076] Received PREPARE: id:1741322995010, from:30078, delay:0.0002s, distance:280.69m (Euclidean)
[2025-03-07 13:49:56,505] [INFO] [30076] Received PREPARE: id:1741322995010, from:30066, delay:0.0001s, distance:181.37m (Euclidean)
[2025-03-07 13:49:56,505] [INFO] [30076] Received PREPARE: id:1741322995010, from:30011, delay:0.0000s, distance:118.98m (Euclidean)
[2025-03-07 13:49:56,505] [INFO] [30076] Received COMMIT: id:1741322995010, from:30078, delay:0.0002s, distance:280.69m (Euclidean)
[2025-03-07 13:49:56,505] [INFO] [30076] Received COMMIT: id:1741322995010, from:30066, delay:0.0001s, distance:181.37m (Euclidean)
[2025-03-07 13:49:56,507] [INFO] [30076] Received COMMIT: id:1741322995010, from:30063, delay:0.0001s, distance:243.81m (Euclidean)
[2025-03-07 13:49:56,507] [INFO] [30076] Received COMMIT: id:1741322995010, from:30045, delay:0.0001s, distance:219.82m (Euclidean)
[2025-03-07 13:49:56,507] [INFO] [30076] Received PREPARE: id:1741322995010, from:30045, delay:0.0001s, distance:219.82m (Euclidean)
[2025-03-07 13:49:56,507] [INFO] [30076] Received COMMIT: id:1741322995010, from:30057, delay:0.0000s, distance:118.06m (Euclidean)
[2025-03-07 13:49:56,507] [INFO] [30076] Received PREPARE: id:1741322995010, from:30057, delay:0.0000s, distance:118.06m (Euclidean)
[2025-03-07 13:49:56,514] [INFO] [30076] Received COMMIT: id:1741322995010, from:30014, delay:0.0000s, distance:128.28m (Euclidean)
[2025-03-07 13:49:56,514] [INFO] [30076] Received COMMIT: id:1741322995010, from:30039, delay:0.0000s, distance:136.17m (Euclidean)
[2025-03-07 13:49:56,549] [INFO] [30076] Received COMMIT: id:1741322995010, from:30000, delay:0.0000s, distance:162.75m (Euclidean)
[2025-03-07 13:49:56,549] [INFO] [30076] Received COMMIT: id:1741322995010, from:30019, delay:0.0001s, distance:199.81m (Euclidean)
[2025-03-07 13:49:56,549] [INFO] [30076] Received PREPARE: id:1741322995010, from:30018, delay:0.0000s, distance:142.99m (Euclidean)
[2025-03-07 13:49:56,688] [INFO] [30076] Received COMMIT: id:1741322995010, from:30005, delay:0.0000s, distance:194.12m (Euclidean)
[2025-03-07 13:49:56,688] [INFO] [30076] Received PREPARE: id:1741322995010, from:30056, delay:0.0002s, distance:289.60m (Euclidean)
[2025-03-07 13:49:56,688] [INFO] [30076] Received PREPARE: id:1741322995010, from:30016, delay:0.0001s, distance:245.70m (Euclidean)
[2025-03-07 13:49:56,688] [INFO] [30076] Received PREPARE: id:1741322995010, from:30005, delay:0.0000s, distance:194.12m (Euclidean)
[2025-03-07 13:49:56,693] [INFO] [30076] Received COMMIT: id:1741322995010, from:30016, delay:0.0001s, distance:245.70m (Euclidean)
[2025-03-07 13:49:56,700] [INFO] [30076] Received COMMIT: id:1741322995010, from:30006, delay:0.0000s, distance:131.02m (Euclidean)
[2025-03-07 13:49:56,700] [INFO] [30076] Received PREPARE: id:1741322995010, from:30007, delay:0.0000s, distance:145.32m (Euclidean)
[2025-03-07 13:49:56,713] [INFO] [30076] Received PREPARE: id:1741322995010, from:30031, delay:0.0000s, distance:105.21m (Euclidean)
[2025-03-07 13:49:56,713] [INFO] [30076] Received COMMIT: id:1741322995010, from:30056, delay:0.0002s, distance:289.60m (Euclidean)
[2025-03-07 13:49:56,713] [INFO] [30076] Received COMMIT: id:1741322995010, from:30031, delay:0.0000s, distance:105.21m (Euclidean)
[2025-03-07 13:49:56,713] [INFO] [30076] Received PREPARE: id:1741322995010, from:30010, delay:0.0001s, distance:174.35m (Euclidean)
[2025-03-07 13:49:56,729] [INFO] [30076] Received COMMIT: id:1741322995010, from:30037, delay:0.0001s, distance:160.62m (Euclidean)
[2025-03-07 13:49:56,729] [INFO] [30076] Received PREPARE: id:1741322995010, from:30037, delay:0.0001s, distance:160.62m (Euclidean)
[2025-03-07 13:49:56,742] [INFO] [30076] Received PREPARE: id:1741322995010, from:30025, delay:0.0000s, distance:197.74m (Euclidean)
[2025-03-07 13:49:56,756] [INFO] [30076] Received COMMIT: id:1741322995010, from:30025, delay:0.0000s, distance:197.74m (Euclidean)
[2025-03-07 13:49:56,756] [INFO] [30076] Received PREPARE: id:1741322995010, from:30069, delay:0.0000s, distance:60.72m (Euclidean)
[2025-03-07 13:49:56,786] [INFO] [30076] Received PREPARE: id:1741322995010, from:30055, delay:0.0000s, distance:146.04m (Euclidean)
[2025-03-07 13:49:56,790] [INFO] [30076] Received COMMIT: id:1741322995010, from:30018, delay:0.0000s, distance:142.99m (Euclidean)
[2025-03-07 13:49:56,803] [INFO] [30076] Received COMMIT: id:1741322995010, from:30069, delay:0.0000s, distance:60.72m (Euclidean)
[2025-03-07 13:49:56,803] [INFO] [30076] Received COMMIT: id:1741322995010, from:30011, delay:0.0000s, distance:118.98m (Euclidean)
[2025-03-07 13:49:56,827] [INFO] [30076] Received COMMIT: id:1741322995010, from:30055, delay:0.0000s, distance:146.04m (Euclidean)
[2025-03-07 13:49:56,830] [INFO] [30076] Received PREPARE: id:1741322995010, from:30004, delay:0.0002s, distance:283.37m (Euclidean)
[2025-03-07 13:49:56,851] [INFO] [30076] Received PREPARE: id:1741322995010, from:30032, delay:0.0001s, distance:247.86m (Euclidean)
[2025-03-07 13:49:56,853] [INFO] [30076] Received PREPARE: id:1741322995010, from:30073, delay:0.0002s, distance:288.09m (Euclidean)
[2025-03-07 13:49:56,853] [INFO] [30076] Received PREPARE: id:1741322995010, from:30023, delay:0.0001s, distance:207.72m (Euclidean)
[2025-03-07 13:49:56,853] [INFO] [30076] Received COMMIT: id:1741322995010, from:30032, delay:0.0001s, distance:247.86m (Euclidean)
[2025-03-07 13:49:56,888] [INFO] [30076] Received COMMIT: id:1741322995010, from:30004, delay:0.0002s, distance:283.37m (Euclidean)
[2025-03-07 13:49:56,924] [INFO] [30076] Received COMMIT: id:1741322995010, from:30007, delay:0.0000s, distance:145.32m (Euclidean)
[2025-03-07 13:49:56,956] [INFO] [30076] Received COMMIT: id:1741322995010, from:30073, delay:0.0002s, distance:288.09m (Euclidean)
[2025-03-07 13:49:56,966] [INFO] [30076] Received PREPARE: id:1741322995010, from:30012, delay:0.0001s, distance:237.94m (Euclidean)
[2025-03-07 13:49:56,966] [INFO] [30076] Received COMMIT: id:1741322995010, from:30012, delay:0.0001s, distance:237.94m (Euclidean)
[2025-03-07 13:49:56,968] [INFO] [30076] Received PREPARE: id:1741322995010, from:30044, delay:0.0002s, distance:284.77m (Euclidean)
[2025-03-07 13:49:56,970] [INFO] [30076] Received COMMIT: id:1741322995010, from:30044, delay:0.0002s, distance:284.77m (Euclidean)
[2025-03-07 13:49:56,995] [INFO] [30076] Received PREPARE: id:1741322995010, from:30027, delay:0.0000s, distance:99.09m (Euclidean)
[2025-03-07 13:49:56,995] [INFO] [30076] Received PREPARE: id:1741322995010, from:30040, delay:0.0001s, distance:215.81m (Euclidean)
[2025-03-07 13:49:57,010] [INFO] [30076] Received COMMIT: id:1741322995010, from:30027, delay:0.0000s, distance:99.09m (Euclidean)
[2025-03-07 13:49:57,010] [INFO] [30076] Received PREPARE: id:1741322995010, from:30003, delay:0.0001s, distance:216.48m (Euclidean)
[2025-03-07 13:49:57,019] [INFO] [30076] Received COMMIT: id:1741322995010, from:30040, delay:0.0001s, distance:215.81m (Euclidean)
[2025-03-07 13:49:57,019] [INFO] [30076] Received COMMIT: id:1741322995010, from:30003, delay:0.0001s, distance:216.48m (Euclidean)
[2025-03-07 13:49:57,021] [INFO] [30076] Received COMMIT: id:1741322995010, from:30010, delay:0.0001s, distance:174.35m (Euclidean)
[2025-03-07 13:49:57,030] [INFO] [30076] Received PREPARE: id:1741322995010, from:30049, delay:0.0002s, distance:288.80m (Euclidean)
[2025-03-07 13:49:57,030] [INFO] [30076] Received PREPARE: id:1741322995010, from:30058, delay:0.0001s, distance:238.77m (Euclidean)
[2025-03-07 13:49:57,030] [INFO] [30076] Received PREPARE: id:1741322995010, from:30067, delay:0.0002s, distance:284.01m (Euclidean)
[2025-03-07 13:49:57,030] [INFO] [30076] Received COMMIT: id:1741322995010, from:30049, delay:0.0002s, distance:288.80m (Euclidean)
[2025-03-07 13:49:57,035] [INFO] [30076] Received PREPARE: id:1741322995010, from:30033, delay:0.0001s, distance:194.42m (Euclidean)
[2025-03-07 13:49:57,035] [INFO] [30076] Received PREPARE: id:1741322995010, from:30048, delay:0.0001s, distance:185.82m (Euclidean)
[2025-03-07 13:49:57,035] [INFO] [30076] Received COMMIT: id:1741322995010, from:30058, delay:0.0001s, distance:238.77m (Euclidean)
[2025-03-07 13:49:57,037] [INFO] [30076] Received COMMIT: id:1741322995010, from:30033, delay:0.0001s, distance:194.42m (Euclidean)
[2025-03-07 13:49:57,037] [INFO] [30076] Received COMMIT: id:1741322995010, from:30048, delay:0.0001s, distance:185.82m (Euclidean)
[2025-03-07 13:49:57,039] [INFO] [30076] Received COMMIT: id:1741322995010, from:30067, delay:0.0002s, distance:284.01m (Euclidean)
[2025-03-07 13:49:57,066] [INFO] [30076] Received PREPARE: id:1741322995010, from:30052, delay:0.0002s, distance:296.30m (Euclidean)
[2025-03-07 13:49:57,066] [INFO] [30076] Received PREPARE: id:1741322995010, from:30062, delay:0.0001s, distance:245.93m (Euclidean)
[2025-03-07 13:49:57,066] [INFO] [30076] Received COMMIT: id:1741322995010, from:30062, delay:0.0001s, distance:245.93m (Euclidean)
[2025-03-07 13:49:57,078] [INFO] [30076] Received PREPARE: id:1741322995010, from:30060, delay:0.0001s, distance:207.95m (Euclidean)
[2025-03-07 13:49:57,090] [INFO] [30076] Received PREPARE: id:1741322995010, from:30059, delay:0.0000s, distance:184.39m (Euclidean)
[2025-03-07 13:49:57,090] [INFO] [30076] Received COMMIT: id:1741322995010, from:30052, delay:0.0002s, distance:296.30m (Euclidean)
[2025-03-07 13:49:57,104] [INFO] [30076] Received COMMIT: id:1741322995010, from:30060, delay:0.0001s, distance:207.95m (Euclidean)
[2025-03-07 13:49:57,104] [INFO] [30076] Received COMMIT: id:1741322995010, from:30059, delay:0.0000s, distance:184.39m (Euclidean)
[2025-03-07 13:49:57,169] [INFO] [30076] Received PREPARE: id:1741322995010, from:30022, delay:0.0002s, distance:282.07m (Euclidean)
[2025-03-07 13:49:57,176] [INFO] [30076] Received COMMIT: id:1741322995010, from:30022, delay:0.0002s, distance:282.07m (Euclidean)
[2025-03-07 13:49:57,217] [INFO] [30076] Received COMMIT: id:1741322995010, from:30023, delay:0.0001s, distance:207.72m (Euclidean)
[2025-03-07 13:49:57,217] [INFO] [30076] Received PREPARE: id:1741322995010, from:30017, delay:0.0000s, distance:117.41m (Euclidean)
[2025-03-07 13:49:57,223] [INFO] [30076] Received PREPARE: id:1741322995010, from:30013, delay:0.0002s, distance:278.72m (Euclidean)
[2025-03-07 13:49:57,223] [INFO] [30076] Received PREPARE: id:1741322995010, from:30070, delay:0.0000s, distance:124.13m (Euclidean)
[2025-03-07 13:49:57,223] [INFO] [30076] Received COMMIT: id:1741322995010, from:30017, delay:0.0000s, distance:117.41m (Euclidean)
[2025-03-07 13:49:57,223] [INFO] [30076] Received COMMIT: id:1741322995010, from:30013, delay:0.0002s, distance:278.72m (Euclidean)
[2025-03-07 13:49:57,223] [INFO] [30076] Received PREPARE: id:1741322995010, from:30008, delay:0.0002s, distance:275.52m (Euclidean)
[2025-03-07 13:49:57,226] [INFO] [30076] Received COMMIT: id:1741322995010, from:30008, delay:0.0002s, distance:275.52m (Euclidean)
[2025-03-07 13:49:57,237] [INFO] [30076] Received COMMIT: id:1741322995010, from:30070, delay:0.0000s, distance:124.13m (Euclidean)
[2025-03-07 13:49:57,237] [INFO] [30076] Received PREPARE: id:1741322995010, from:30002, delay:0.0001s, distance:222.35m (Euclidean)
[2025-03-07 13:49:57,248] [INFO] [30076] Received PREPARE: id:1741322995010, from:30074, delay:0.0001s, distance:204.31m (Euclidean)
[2025-03-07 13:49:57,254] [INFO] [30076] Received COMMIT: id:1741322995010, from:30002, delay:0.0001s, distance:222.35m (Euclidean)
[2025-03-07 13:49:57,254] [INFO] [30076] Received PREPARE: id:1741322995010, from:30051, delay:0.0002s, distance:260.44m (Euclidean)
[2025-03-07 13:49:57,254] [INFO] [30076] Received COMMIT: id:1741322995010, from:30051, delay:0.0002s, distance:260.44m (Euclidean)
[2025-03-07 13:49:57,254] [INFO] [30076] Received PREPARE: id:1741322995010, from:30034, delay:0.0002s, distance:298.15m (Euclidean)
[2025-03-07 13:49:57,262] [INFO] [30076] Received COMMIT: id:1741322995010, from:30034, delay:0.0002s, distance:298.15m (Euclidean)
[2025-03-07 13:49:57,262] [INFO] [30076] Received COMMIT: id:1741322995010, from:30074, delay:0.0001s, distance:204.31m (Euclidean)
[2025-03-07 13:49:57,273] [INFO] [30076] Received PREPARE: id:1741322995010, from:30064, delay:0.0001s, distance:243.31m (Euclidean)
[2025-03-07 13:49:57,279] [INFO] [30076] Received PREPARE: id:1741322995010, from:30028, delay:0.0001s, distance:228.43m (Euclidean)
[2025-03-07 13:49:57,283] [INFO] [30076] Received PREPARE: id:1741322995010, from:30035, delay:0.0002s, distance:292.21m (Euclidean)
[2025-03-07 13:49:57,283] [INFO] [30076] Received COMMIT: id:1741322995010, from:30064, delay:0.0001s, distance:243.31m (Euclidean)
[2025-03-07 13:49:57,286] [INFO] [30076] Received COMMIT: id:1741322995010, from:30028, delay:0.0001s, distance:228.43m (Euclidean)
[2025-03-07 13:49:57,291] [INFO] [30076] Received COMMIT: id:1741322995010, from:30035, delay:0.0002s, distance:292.21m (Euclidean)
[2025-03-07 13:49:57,302] [INFO] [30076] Received PREPARE: id:1741322995010, from:30042, delay:0.0001s, distance:214.88m (Euclidean)
[2025-03-07 13:49:57,312] [INFO] [30076] Received COMMIT: id:1741322995010, from:30042, delay:0.0001s, distance:214.88m (Euclidean)
[2025-03-07 13:49:57,317] [INFO] [30076] Received PREPARE: id:1741322995010, from:30038, delay:0.0002s, distance:281.83m (Euclidean)
[2025-03-07 13:49:57,317] [INFO] [30076] Received COMMIT: id:1741322995010, from:30038, delay:0.0002s, distance:281.83m (Euclidean)
[2025-03-07 13:50:40,686] [INFO] Starting node at localhost:30076 | index= 77 | f=1, k=4 | Role: Replica
[2025-03-07 13:51:24,402] [INFO] Starting node at localhost:30076 | index= 77 | f=1, k=4 | Role: Replica
[2025-03-07 13:51:35,423] [INFO] [30076] Received PRE-PREPARE: id:1741323095323, from:Leader(30000), delay:0.0000s, distance:106.95m (Euclidean)
[2025-03-07 13:51:35,423] [INFO] [30076] Broadcasting PREPARE for REQUEST 1741323095323
[2025-03-07 13:51:35,768] [INFO] [30076] Received PREPARE: id:1741323095323, from:30088, delay:0.0000s, distance:100.46m (Euclidean)
[2025-03-07 13:51:35,799] [INFO] [30076] Received PREPARE: id:1741323095323, from:30101, delay:0.0000s, distance:249.52m (Euclidean)
[2025-03-07 13:51:35,799] [INFO] [30076] Broadcasting COMMIT for REQUEST 1741323095323
[2025-03-07 13:51:36,079] [INFO] [30076] Received PREPARE: id:1741323095323, from:30096, delay:0.0000s, distance:67.69m (Euclidean)
[2025-03-07 13:51:36,080] [INFO] [30076] Received PREPARE: id:1741323095323, from:30106, delay:0.0000s, distance:143.54m (Euclidean)
[2025-03-07 13:51:36,080] [INFO] [30076] Received PREPARE: id:1741323095323, from:30104, delay:0.0000s, distance:142.56m (Euclidean)
[2025-03-07 13:51:36,080] [INFO] [30076] Received PREPARE: id:1741323095323, from:30111, delay:0.0000s, distance:54.98m (Euclidean)
[2025-03-07 13:51:36,135] [INFO] [30076] Received PREPARE: id:1741323095323, from:30102, delay:0.0001s, distance:170.78m (Euclidean)
[2025-03-07 13:51:36,139] [INFO] [30076] Received PREPARE: id:1741323095323, from:30067, delay:0.0000s, distance:79.89m (Euclidean)
[2025-03-07 13:51:36,139] [INFO] [30076] Received PREPARE: id:1741323095323, from:30108, delay:0.0001s, distance:195.43m (Euclidean)
[2025-03-07 13:51:36,139] [INFO] [30076] Received PREPARE: id:1741323095323, from:30057, delay:0.0000s, distance:69.74m (Euclidean)
[2025-03-07 13:51:36,139] [INFO] [30076] Received PREPARE: id:1741323095323, from:30114, delay:0.0001s, distance:181.69m (Euclidean)
[2025-03-07 13:51:36,162] [INFO] [30076] Received COMMIT: id:1741323095323, from:30104, delay:0.0000s, distance:142.56m (Euclidean)
[2025-03-07 13:51:36,169] [INFO] [30076] Received PREPARE: id:1741323095323, from:30117, delay:0.0000s, distance:139.16m (Euclidean)
[2025-03-07 13:51:36,169] [INFO] [30076] Received PREPARE: id:1741323095323, from:30110, delay:0.0000s, distance:98.23m (Euclidean)
[2025-03-07 13:51:36,189] [INFO] [30076] Received PREPARE: id:1741323095323, from:30075, delay:0.0000s, distance:114.02m (Euclidean)
[2025-03-07 13:51:36,219] [INFO] [30076] Received PREPARE: id:1741323095323, from:30097, delay:0.0000s, distance:149.08m (Euclidean)
[2025-03-07 13:51:36,219] [INFO] [30076] Received COMMIT: id:1741323095323, from:30101, delay:0.0000s, distance:249.52m (Euclidean)
[2025-03-07 13:51:36,219] [INFO] [LEADER 30076] Sending REPLY for REQUEST 1741323095323 to CLIENT
[2025-03-07 13:51:36,219] [INFO] [30076] Received COMMIT: id:1741323095323, from:30067, delay:0.0000s, distance:79.89m (Euclidean)
[2025-03-07 13:51:36,236] [INFO] [30076] Received PREPARE: id:1741323095323, from:30119, delay:0.0000s, distance:164.17m (Euclidean)
[2025-03-07 13:51:36,236] [INFO] [30076] Received COMMIT: id:1741323095323, from:30110, delay:0.0000s, distance:98.23m (Euclidean)
[2025-03-07 13:51:36,263] [INFO] [30076] Received COMMIT: id:1741323095323, from:30102, delay:0.0001s, distance:170.78m (Euclidean)
[2025-03-07 13:51:36,263] [INFO] [30076] Received PREPARE: id:1741323095323, from:30112, delay:0.0000s, distance:134.06m (Euclidean)
[2025-03-07 13:51:36,263] [INFO] [30076] Received PREPARE: id:1741323095323, from:30026, delay:0.0000s, distance:84.55m (Euclidean)
[2025-03-07 13:51:36,292] [INFO] [30076] Received COMMIT: id:1741323095323, from:30117, delay:0.0000s, distance:139.16m (Euclidean)
[2025-03-07 13:51:36,299] [INFO] [30076] Received COMMIT: id:1741323095323, from:30112, delay:0.0000s, distance:134.06m (Euclidean)
[2025-03-07 13:51:36,309] [INFO] [30076] Received PREPARE: id:1741323095323, from:30004, delay:0.0000s, distance:58.27m (Euclidean)
[2025-03-07 13:51:36,337] [INFO] [30076] Received PREPARE: id:1741323095323, from:30020, delay:0.0000s, distance:135.97m (Euclidean)
[2025-03-07 13:51:36,348] [INFO] [30076] Received COMMIT: id:1741323095323, from:30119, delay:0.0000s, distance:164.17m (Euclidean)
[2025-03-07 13:51:36,371] [INFO] [30076] Received PREPARE: id:1741323095323, from:30099, delay:0.0000s, distance:45.97m (Euclidean)
[2025-03-07 13:51:36,371] [INFO] [30076] Received PREPARE: id:1741323095323, from:30109, delay:0.0000s, distance:115.74m (Euclidean)
[2025-03-07 13:51:36,392] [INFO] [30076] Received PREPARE: id:1741323095323, from:30107, delay:0.0001s, distance:206.66m (Euclidean)
[2025-03-07 13:51:36,395] [INFO] [30076] Received PREPARE: id:1741323095323, from:30055, delay:0.0000s, distance:129.62m (Euclidean)
[2025-03-07 13:51:36,427] [INFO] [30076] Received COMMIT: id:1741323095323, from:30106, delay:0.0000s, distance:143.54m (Euclidean)
[2025-03-07 13:51:36,428] [INFO] [30076] Received COMMIT: id:1741323095323, from:30107, delay:0.0001s, distance:206.66m (Euclidean)
[2025-03-07 13:51:36,432] [INFO] [30076] Received COMMIT: id:1741323095323, from:30108, delay:0.0001s, distance:195.43m (Euclidean)
[2025-03-07 13:51:36,477] [INFO] [30076] Received PREPARE: id:1741323095323, from:30009, delay:0.0000s, distance:177.69m (Euclidean)
[2025-03-07 13:51:36,477] [INFO] [30076] Received COMMIT: id:1741323095323, from:30075, delay:0.0000s, distance:114.02m (Euclidean)
[2025-03-07 13:51:36,481] [INFO] [30076] Received COMMIT: id:1741323095323, from:30055, delay:0.0000s, distance:129.62m (Euclidean)
[2025-03-07 13:51:36,493] [INFO] [30076] Received COMMIT: id:1741323095323, from:30057, delay:0.0000s, distance:69.74m (Euclidean)
[2025-03-07 13:51:36,555] [INFO] [30076] Received PREPARE: id:1741323095323, from:30017, delay:0.0000s, distance:136.13m (Euclidean)
[2025-03-07 13:51:36,555] [INFO] [30076] Received COMMIT: id:1741323095323, from:30114, delay:0.0001s, distance:181.69m (Euclidean)
[2025-03-07 13:51:36,555] [INFO] [30076] Received PREPARE: id:1741323095323, from:30005, delay:0.0000s, distance:144.85m (Euclidean)
[2025-03-07 13:51:36,555] [INFO] [30076] Received PREPARE: id:1741323095323, from:30113, delay:0.0001s, distance:236.09m (Euclidean)
[2025-03-07 13:51:36,573] [INFO] [30076] Received PREPARE: id:1741323095323, from:30037, delay:0.0000s, distance:36.64m (Euclidean)
[2025-03-07 13:51:36,575] [INFO] [30076] Received PREPARE: id:1741323095323, from:30094, delay:0.0002s, distance:251.72m (Euclidean)
[2025-03-07 13:51:36,575] [INFO] [30076] Received COMMIT: id:1741323095323, from:30094, delay:0.0002s, distance:251.72m (Euclidean)
[2025-03-07 13:51:36,585] [INFO] [30076] Received PREPARE: id:1741323095323, from:30021, delay:0.0000s, distance:111.93m (Euclidean)
[2025-03-07 13:51:36,587] [INFO] [30076] Received COMMIT: id:1741323095323, from:30004, delay:0.0000s, distance:58.27m (Euclidean)
[2025-03-07 13:51:36,594] [INFO] [30076] Received COMMIT: id:1741323095323, from:30113, delay:0.0001s, distance:236.09m (Euclidean)
[2025-03-07 13:51:36,596] [INFO] [30076] Received PREPARE: id:1741323095323, from:30052, delay:0.0000s, distance:127.98m (Euclidean)
[2025-03-07 13:51:36,603] [INFO] [30076] Received PREPARE: id:1741323095323, from:30006, delay:0.0000s, distance:155.13m (Euclidean)
[2025-03-07 13:51:36,603] [INFO] [30076] Received PREPARE: id:1741323095323, from:30103, delay:0.0000s, distance:137.11m (Euclidean)
[2025-03-07 13:51:36,624] [INFO] [30076] Received COMMIT: id:1741323095323, from:30103, delay:0.0000s, distance:137.11m (Euclidean)
[2025-03-07 13:51:36,624] [INFO] [30076] Received PREPARE: id:1741323095323, from:30029, delay:0.0001s, distance:219.14m (Euclidean)
[2025-03-07 13:51:36,626] [INFO] [30076] Received COMMIT: id:1741323095323, from:30029, delay:0.0001s, distance:219.14m (Euclidean)
[2025-03-07 13:51:36,626] [INFO] [30076] Received COMMIT: id:1741323095323, from:30037, delay:0.0000s, distance:36.64m (Euclidean)
[2025-03-07 13:51:36,628] [INFO] [30076] Received COMMIT: id:1741323095323, from:30111, delay:0.0000s, distance:54.98m (Euclidean)
[2025-03-07 13:51:36,670] [INFO] [30076] Received COMMIT: id:1741323095323, from:30097, delay:0.0000s, distance:149.08m (Euclidean)
[2025-03-07 13:51:36,675] [INFO] [30076] Received PREPARE: id:1741323095323, from:30027, delay:0.0001s, distance:174.50m (Euclidean)
[2025-03-07 13:51:36,675] [INFO] [30076] Received PREPARE: id:1741323095323, from:30010, delay:0.0000s, distance:102.63m (Euclidean)
[2025-03-07 13:51:36,682] [INFO] [30076] Received COMMIT: id:1741323095323, from:30088, delay:0.0000s, distance:100.46m (Euclidean)
[2025-03-07 13:51:36,682] [INFO] [30076] Received PREPARE: id:1741323095323, from:30016, delay:0.0000s, distance:131.98m (Euclidean)
[2025-03-07 13:51:36,682] [INFO] [30076] Received PREPARE: id:1741323095323, from:30082, delay:0.0001s, distance:181.88m (Euclidean)
[2025-03-07 13:51:36,682] [INFO] [30076] Received COMMIT: id:1741323095323, from:30082, delay:0.0001s, distance:181.88m (Euclidean)
[2025-03-07 13:51:36,682] [INFO] [30076] Received COMMIT: id:1741323095323, from:30016, delay:0.0000s, distance:131.98m (Euclidean)
[2025-03-07 13:51:36,682] [INFO] [30076] Received PREPARE: id:1741323095323, from:30031, delay:0.0000s, distance:42.53m (Euclidean)
[2025-03-07 13:51:36,707] [INFO] [30076] Received COMMIT: id:1741323095323, from:30021, delay:0.0000s, distance:111.93m (Euclidean)
[2025-03-07 13:51:36,733] [INFO] [30076] Received COMMIT: id:1741323095323, from:30096, delay:0.0000s, distance:67.69m (Euclidean)
[2025-03-07 13:51:36,739] [INFO] [30076] Received COMMIT: id:1741323095323, from:30006, delay:0.0000s, distance:155.13m (Euclidean)
[2025-03-07 13:51:36,747] [INFO] [30076] Received PREPARE: id:1741323095323, from:30069, delay:0.0000s, distance:132.89m (Euclidean)
[2025-03-07 13:51:36,747] [INFO] [30076] Received COMMIT: id:1741323095323, from:30099, delay:0.0000s, distance:45.97m (Euclidean)
[2025-03-07 13:51:36,747] [INFO] [30076] Received PREPARE: id:1741323095323, from:30060, delay:0.0001s, distance:197.82m (Euclidean)
[2025-03-07 13:51:36,747] [INFO] [30076] Received COMMIT: id:1741323095323, from:30109, delay:0.0000s, distance:115.74m (Euclidean)
[2025-03-07 13:51:36,808] [INFO] [30076] Received PREPARE: id:1741323095323, from:30001, delay:0.0002s, distance:291.26m (Euclidean)
[2025-03-07 13:51:36,808] [INFO] [30076] Received COMMIT: id:1741323095323, from:30020, delay:0.0000s, distance:135.97m (Euclidean)
[2025-03-07 13:51:36,813] [INFO] [30076] Received COMMIT: id:1741323095323, from:30069, delay:0.0000s, distance:132.89m (Euclidean)
[2025-03-07 13:51:36,863] [INFO] [30076] Received PREPARE: id:1741323095323, from:30040, delay:0.0001s, distance:163.65m (Euclidean)
[2025-03-07 13:51:36,863] [INFO] [30076] Received COMMIT: id:1741323095323, from:30009, delay:0.0000s, distance:177.69m (Euclidean)
[2025-03-07 13:51:36,871] [INFO] [30076] Received COMMIT: id:1741323095323, from:30010, delay:0.0000s, distance:102.63m (Euclidean)
[2025-03-07 13:51:36,871] [INFO] [30076] Received COMMIT: id:1741323095323, from:30040, delay:0.0001s, distance:163.65m (Euclidean)
[2025-03-07 13:51:36,887] [INFO] [30076] Received PREPARE: id:1741323095323, from:30032, delay:0.0002s, distance:268.42m (Euclidean)
[2025-03-07 13:51:36,887] [INFO] [30076] Received COMMIT: id:1741323095323, from:30032, delay:0.0002s, distance:268.42m (Euclidean)
[2025-03-07 13:51:36,907] [INFO] [30076] Received PREPARE: id:1741323095323, from:30011, delay:0.0001s, distance:179.56m (Euclidean)
[2025-03-07 13:51:36,907] [INFO] [30076] Received PREPARE: id:1741323095323, from:30041, delay:0.0000s, distance:182.22m (Euclidean)
[2025-03-07 13:51:36,926] [INFO] [30076] Received PREPARE: id:1741323095323, from:30050, delay:0.0001s, distance:243.47m (Euclidean)
[2025-03-07 13:51:36,928] [INFO] [30076] Received COMMIT: id:1741323095323, from:30050, delay:0.0001s, distance:243.47m (Euclidean)
[2025-03-07 13:51:36,930] [INFO] [30076] Received PREPARE: id:1741323095323, from:30095, delay:0.0001s, distance:167.88m (Euclidean)
[2025-03-07 13:51:36,948] [INFO] [30076] Received COMMIT: id:1741323095323, from:30095, delay:0.0001s, distance:167.88m (Euclidean)
[2025-03-07 13:51:36,969] [INFO] [30076] Received PREPARE: id:1741323095323, from:30092, delay:0.0000s, distance:95.44m (Euclidean)
[2025-03-07 13:51:36,969] [INFO] [30076] Received COMMIT: id:1741323095323, from:30092, delay:0.0000s, distance:95.44m (Euclidean)
[2025-03-07 13:51:36,981] [INFO] [30076] Received PREPARE: id:1741323095323, from:30022, delay:0.0000s, distance:58.62m (Euclidean)
[2025-03-07 13:51:36,991] [INFO] [30076] Received PREPARE: id:1741323095323, from:30008, delay:0.0001s, distance:241.57m (Euclidean)
[2025-03-07 13:51:37,046] [INFO] [30076] Received PREPARE: id:1741323095323, from:30014, delay:0.0000s, distance:126.77m (Euclidean)
[2025-03-07 13:51:37,046] [INFO] [30076] Received COMMIT: id:1741323095323, from:30060, delay:0.0001s, distance:197.82m (Euclidean)
[2025-03-07 13:51:37,046] [INFO] [30076] Received PREPARE: id:1741323095323, from:30025, delay:0.0000s, distance:159.11m (Euclidean)
[2025-03-07 13:51:37,070] [INFO] [30076] Received COMMIT: id:1741323095323, from:30031, delay:0.0000s, distance:42.53m (Euclidean)
[2025-03-07 13:51:37,072] [INFO] [30076] Received COMMIT: id:1741323095323, from:30041, delay:0.0000s, distance:182.22m (Euclidean)
[2025-03-07 13:51:37,116] [INFO] [30076] Received PREPARE: id:1741323095323, from:30002, delay:0.0000s, distance:183.33m (Euclidean)
[2025-03-07 13:51:37,116] [INFO] [30076] Received COMMIT: id:1741323095323, from:30005, delay:0.0000s, distance:144.85m (Euclidean)
[2025-03-07 13:51:37,124] [INFO] [30076] Received PREPARE: id:1741323095323, from:30074, delay:0.0000s, distance:106.81m (Euclidean)
[2025-03-07 13:51:37,124] [INFO] [30076] Received COMMIT: id:1741323095323, from:30074, delay:0.0000s, distance:106.81m (Euclidean)
[2025-03-07 13:51:37,124] [INFO] [30076] Received COMMIT: id:1741323095323, from:30017, delay:0.0000s, distance:136.13m (Euclidean)
[2025-03-07 13:51:37,156] [INFO] [30076] Received COMMIT: id:1741323095323, from:30008, delay:0.0001s, distance:241.57m (Euclidean)
[2025-03-07 13:51:37,193] [INFO] [30076] Received COMMIT: id:1741323095323, from:30011, delay:0.0001s, distance:179.56m (Euclidean)
[2025-03-07 13:51:37,211] [INFO] [30076] Received COMMIT: id:1741323095323, from:30001, delay:0.0002s, distance:291.26m (Euclidean)
[2025-03-07 13:51:37,222] [INFO] [30076] Received COMMIT: id:1741323095323, from:30022, delay:0.0000s, distance:58.62m (Euclidean)
[2025-03-07 13:51:37,265] [INFO] [30076] Received PREPARE: id:1741323095323, from:30053, delay:0.0002s, distance:271.01m (Euclidean)
[2025-03-07 13:51:37,296] [INFO] [30076] Received COMMIT: id:1741323095323, from:30002, delay:0.0000s, distance:183.33m (Euclidean)
[2025-03-07 13:51:37,309] [INFO] [30076] Received PREPARE: id:1741323095323, from:30051, delay:0.0000s, distance:111.21m (Euclidean)
[2025-03-07 13:51:37,309] [INFO] [30076] Received PREPARE: id:1741323095323, from:30116, delay:0.0000s, distance:127.44m (Euclidean)
[2025-03-07 13:51:37,315] [INFO] [30076] Received COMMIT: id:1741323095323, from:30116, delay:0.0000s, distance:127.44m (Euclidean)
[2025-03-07 13:51:37,368] [INFO] [30076] Received PREPARE: id:1741323095323, from:30033, delay:0.0000s, distance:123.46m (Euclidean)
[2025-03-07 13:51:37,368] [INFO] [30076] Received PREPARE: id:1741323095323, from:30023, delay:0.0000s, distance:175.89m (Euclidean)
[2025-03-07 13:51:37,378] [INFO] [30076] Received PREPARE: id:1741323095323, from:30030, delay:0.0001s, distance:206.72m (Euclidean)
[2025-03-07 13:51:37,421] [INFO] [30076] Received COMMIT: id:1741323095323, from:30023, delay:0.0000s, distance:175.89m (Euclidean)
[2025-03-07 13:51:37,426] [INFO] [30076] Received COMMIT: id:1741323095323, from:30014, delay:0.0000s, distance:126.77m (Euclidean)
[2025-03-07 13:51:37,494] [INFO] [30076] Received COMMIT: id:1741323095323, from:30027, delay:0.0001s, distance:174.50m (Euclidean)
[2025-03-07 13:51:37,525] [INFO] [30076] Received PREPARE: id:1741323095323, from:30043, delay:0.0000s, distance:131.94m (Euclidean)
[2025-03-07 13:51:37,531] [INFO] [30076] Received COMMIT: id:1741323095323, from:30043, delay:0.0000s, distance:131.94m (Euclidean)
[2025-03-07 13:51:37,531] [INFO] [30076] Received COMMIT: id:1741323095323, from:30056, delay:0.0000s, distance:63.59m (Euclidean)
[2025-03-07 13:51:37,531] [INFO] [30076] Received PREPARE: id:1741323095323, from:30056, delay:0.0000s, distance:63.59m (Euclidean)
[2025-03-07 13:51:37,535] [INFO] [30076] Received COMMIT: id:1741323095323, from:30026, delay:0.0000s, distance:84.55m (Euclidean)
[2025-03-07 13:51:37,553] [INFO] [30076] Received PREPARE: id:1741323095323, from:30046, delay:0.0000s, distance:124.17m (Euclidean)
[2025-03-07 13:51:37,553] [INFO] [30076] Received COMMIT: id:1741323095323, from:30053, delay:0.0002s, distance:271.01m (Euclidean)
[2025-03-07 13:51:37,582] [INFO] [30076] Received PREPARE: id:1741323095323, from:30012, delay:0.0001s, distance:201.87m (Euclidean)
[2025-03-07 13:51:37,582] [INFO] [30076] Received COMMIT: id:1741323095323, from:30012, delay:0.0001s, distance:201.87m (Euclidean)
[2025-03-07 13:51:37,605] [INFO] [30076] Received COMMIT: id:1741323095323, from:30051, delay:0.0000s, distance:111.21m (Euclidean)
[2025-03-07 13:51:37,639] [INFO] [30076] Received COMMIT: id:1741323095323, from:30025, delay:0.0000s, distance:159.11m (Euclidean)
[2025-03-07 13:51:37,740] [INFO] [30076] Received PREPARE: id:1741323095323, from:30042, delay:0.0001s, distance:191.82m (Euclidean)
[2025-03-07 13:51:37,757] [INFO] [30076] Received PREPARE: id:1741323095323, from:30036, delay:0.0000s, distance:172.10m (Euclidean)
[2025-03-07 13:51:37,757] [INFO] [30076] Received PREPARE: id:1741323095323, from:30044, delay:0.0001s, distance:202.83m (Euclidean)
[2025-03-07 13:51:37,761] [INFO] [30076] Received COMMIT: id:1741323095323, from:30036, delay:0.0000s, distance:172.10m (Euclidean)
[2025-03-07 13:51:37,761] [INFO] [30076] Received COMMIT: id:1741323095323, from:30044, delay:0.0001s, distance:202.83m (Euclidean)
[2025-03-07 13:51:37,761] [INFO] [30076] Received PREPARE: id:1741323095323, from:30054, delay:0.0001s, distance:160.05m (Euclidean)
[2025-03-07 13:51:37,761] [INFO] [30076] Received COMMIT: id:1741323095323, from:30054, delay:0.0001s, distance:160.05m (Euclidean)
[2025-03-07 13:51:37,820] [INFO] [30076] Received PREPARE: id:1741323095323, from:30084, delay:0.0001s, distance:247.72m (Euclidean)
[2025-03-07 13:51:37,852] [INFO] [30076] Received COMMIT: id:1741323095323, from:30030, delay:0.0001s, distance:206.72m (Euclidean)
[2025-03-07 13:51:37,852] [INFO] [30076] Received COMMIT: id:1741323095323, from:30084, delay:0.0001s, distance:247.72m (Euclidean)
[2025-03-07 13:51:37,852] [INFO] [30076] Received PREPARE: id:1741323095323, from:30028, delay:0.0001s, distance:220.18m (Euclidean)
[2025-03-07 13:51:37,860] [INFO] [30076] Received COMMIT: id:1741323095323, from:30028, delay:0.0001s, distance:220.18m (Euclidean)
[2025-03-07 13:51:37,865] [INFO] [30076] Received PREPARE: id:1741323095323, from:30003, delay:0.0002s, distance:257.90m (Euclidean)
[2025-03-07 13:51:37,865] [INFO] [30076] Received COMMIT: id:1741323095323, from:30003, delay:0.0002s, distance:257.90m (Euclidean)
[2025-03-07 13:51:37,908] [INFO] [30076] Received PREPARE: id:1741323095323, from:30019, delay:0.0001s, distance:155.13m (Euclidean)
[2025-03-07 13:51:37,919] [INFO] [30076] Received COMMIT: id:1741323095323, from:30019, delay:0.0001s, distance:155.13m (Euclidean)
[2025-03-07 13:51:37,923] [INFO] [30076] Received PREPARE: id:1741323095323, from:30098, delay:0.0000s, distance:148.02m (Euclidean)
[2025-03-07 13:51:37,923] [INFO] [30076] Received COMMIT: id:1741323095323, from:30052, delay:0.0000s, distance:127.98m (Euclidean)
[2025-03-07 13:51:37,947] [INFO] [30076] Received COMMIT: id:1741323095323, from:30046, delay:0.0000s, distance:124.17m (Euclidean)
[2025-03-07 13:51:37,947] [INFO] [30076] Received COMMIT: id:1741323095323, from:30098, delay:0.0000s, distance:148.02m (Euclidean)
[2025-03-07 13:51:37,949] [INFO] [30076] Received PREPARE: id:1741323095323, from:30013, delay:0.0001s, distance:207.80m (Euclidean)
[2025-03-07 13:51:37,954] [INFO] [30076] Received PREPARE: id:1741323095323, from:30079, delay:0.0000s, distance:140.55m (Euclidean)
[2025-03-07 13:51:37,954] [INFO] [30076] Received COMMIT: id:1741323095323, from:30079, delay:0.0000s, distance:140.55m (Euclidean)
[2025-03-07 13:51:37,954] [INFO] [30076] Received COMMIT: id:1741323095323, from:30013, delay:0.0001s, distance:207.80m (Euclidean)
[2025-03-07 13:51:37,995] [INFO] [30076] Received PREPARE: id:1741323095323, from:30024, delay:0.0001s, distance:233.81m (Euclidean)
[2025-03-07 13:51:37,999] [INFO] [30076] Received COMMIT: id:1741323095323, from:30024, delay:0.0001s, distance:233.81m (Euclidean)
[2025-03-07 13:51:38,033] [INFO] [30076] Received COMMIT: id:1741323095323, from:30033, delay:0.0000s, distance:123.46m (Euclidean)
[2025-03-07 13:51:38,033] [INFO] [30076] Received PREPARE: id:1741323095323, from:30015, delay:0.0001s, distance:195.88m (Euclidean)
[2025-03-07 13:51:38,033] [INFO] [30076] Received COMMIT: id:1741323095323, from:30015, delay:0.0001s, distance:195.88m (Euclidean)
[2025-03-07 13:51:38,152] [INFO] [30076] Received COMMIT: id:1741323095323, from:30042, delay:0.0001s, distance:191.82m (Euclidean)
[2025-03-07 13:51:38,224] [INFO] [30076] Received PREPARE: id:1741323095323, from:30065, delay:0.0001s, distance:211.56m (Euclidean)
[2025-03-07 13:51:38,231] [INFO] [30076] Received PREPARE: id:1741323095323, from:30007, delay:0.0001s, distance:218.81m (Euclidean)
[2025-03-07 13:51:38,231] [INFO] [30076] Received COMMIT: id:1741323095323, from:30007, delay:0.0001s, distance:218.81m (Euclidean)
[2025-03-07 13:51:38,231] [INFO] [30076] Received PREPARE: id:1741323095323, from:30047, delay:0.0001s, distance:171.66m (Euclidean)
[2025-03-07 13:51:38,231] [INFO] [30076] Received COMMIT: id:1741323095323, from:30047, delay:0.0001s, distance:171.66m (Euclidean)
[2025-03-07 13:51:38,242] [INFO] [30076] Received COMMIT: id:1741323095323, from:30065, delay:0.0001s, distance:211.56m (Euclidean)
[2025-03-07 13:51:38,341] [INFO] [30076] Received PREPARE: id:1741323095323, from:30090, delay:0.0000s, distance:103.75m (Euclidean)
[2025-03-07 13:51:38,343] [INFO] [30076] Received PREPARE: id:1741323095323, from:30045, delay:0.0000s, distance:158.80m (Euclidean)
[2025-03-07 13:51:38,357] [INFO] [30076] Received COMMIT: id:1741323095323, from:30090, delay:0.0000s, distance:103.75m (Euclidean)
[2025-03-07 13:51:38,357] [INFO] [30076] Received COMMIT: id:1741323095323, from:30045, delay:0.0000s, distance:158.80m (Euclidean)
[2025-03-07 13:51:38,897] [INFO] [30076] Received PREPARE: id:1741323095323, from:30078, delay:0.0001s, distance:219.40m (Euclidean)
[2025-03-07 13:51:38,928] [INFO] [30076] Received COMMIT: id:1741323095323, from:30078, delay:0.0001s, distance:219.40m (Euclidean)
[2025-03-07 13:51:39,641] [INFO] [30076] Received PREPARE: id:1741323095323, from:30048, delay:0.0001s, distance:245.72m (Euclidean)
[2025-03-07 13:51:39,688] [INFO] [30076] Received PREPARE: id:1741323095323, from:30118, delay:0.0000s, distance:138.64m (Euclidean)
[2025-03-07 13:51:39,706] [INFO] [30076] Received PREPARE: id:1741323095323, from:30068, delay:0.0001s, distance:167.39m (Euclidean)
[2025-03-07 13:51:39,720] [INFO] [30076] Received PREPARE: id:1741323095323, from:30018, delay:0.0001s, distance:206.28m (Euclidean)
[2025-03-07 13:51:39,736] [INFO] [30076] Received COMMIT: id:1741323095323, from:30118, delay:0.0000s, distance:138.64m (Euclidean)
[2025-03-07 13:51:39,738] [INFO] [30076] Received PREPARE: id:1741323095323, from:30077, delay:0.0001s, distance:181.70m (Euclidean)
[2025-03-07 13:51:39,770] [INFO] [30076] Received COMMIT: id:1741323095323, from:30048, delay:0.0001s, distance:245.72m (Euclidean)
[2025-03-07 13:51:39,777] [INFO] [30076] Received COMMIT: id:1741323095323, from:30018, delay:0.0001s, distance:206.28m (Euclidean)
[2025-03-07 13:51:39,819] [INFO] [30076] Received COMMIT: id:1741323095323, from:30068, delay:0.0001s, distance:167.39m (Euclidean)
[2025-03-07 13:51:39,846] [INFO] [30076] Received PREPARE: id:1741323095323, from:30035, delay:0.0000s, distance:124.57m (Euclidean)
[2025-03-07 13:51:39,885] [INFO] [30076] Received COMMIT: id:1741323095323, from:30077, delay:0.0001s, distance:181.70m (Euclidean)
[2025-03-07 13:51:39,955] [INFO] [30076] Received PREPARE: id:1741323095323, from:30066, delay:0.0001s, distance:192.37m (Euclidean)
[2025-03-07 13:51:39,976] [INFO] [30076] Received PREPARE: id:1741323095323, from:30083, delay:0.0001s, distance:156.97m (Euclidean)
[2025-03-07 13:51:39,994] [INFO] [30076] Received COMMIT: id:1741323095323, from:30035, delay:0.0000s, distance:124.57m (Euclidean)
[2025-03-07 13:51:40,005] [INFO] [30076] Received COMMIT: id:1741323095323, from:30066, delay:0.0001s, distance:192.37m (Euclidean)
[2025-03-07 13:51:40,054] [INFO] [30076] Received COMMIT: id:1741323095323, from:30083, delay:0.0001s, distance:156.97m (Euclidean)
[2025-03-07 13:51:40,262] [ERROR] [30076] Error sending to http://localhost:30070/prepare: Cannot connect to host localhost:30070 ssl:default [Connect call failed ('127.0.0.1', 30070)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30070)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30070 ssl:default [Connect call failed ('127.0.0.1', 30070)]
[2025-03-07 13:51:41,468] [ERROR] [30076] Error sending to http://localhost:30058/prepare: Cannot connect to host localhost:30058 ssl:default [Connect call failed ('127.0.0.1', 30058)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30058)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30058 ssl:default [Connect call failed ('127.0.0.1', 30058)]
[2025-03-07 13:51:41,468] [ERROR] [30076] Error sending to http://localhost:30062/prepare: Cannot connect to host localhost:30062 ssl:default [Connect call failed ('127.0.0.1', 30062)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30062)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30062 ssl:default [Connect call failed ('127.0.0.1', 30062)]
[2025-03-07 13:51:41,468] [ERROR] [30076] Error sending to http://localhost:30086/prepare: Cannot connect to host localhost:30086 ssl:default [Connect call failed ('127.0.0.1', 30086)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30086)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30086 ssl:default [Connect call failed ('127.0.0.1', 30086)]
[2025-03-07 13:51:41,484] [ERROR] [30076] Error sending to http://localhost:30064/prepare: Cannot connect to host localhost:30064 ssl:default [Connect call failed ('127.0.0.1', 30064)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30064)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30064 ssl:default [Connect call failed ('127.0.0.1', 30064)]
[2025-03-07 13:51:41,484] [ERROR] [30076] Error sending to http://localhost:30093/commit: Cannot connect to host localhost:30093 ssl:default [Connect call failed ('::1', 30093, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30093, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30093 ssl:default [Connect call failed ('::1', 30093, 0, 0)]
[2025-03-07 13:51:41,484] [ERROR] [30076] Error sending to http://localhost:30089/prepare: Cannot connect to host localhost:30089 ssl:default [Connect call failed ('127.0.0.1', 30089)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30089)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30089 ssl:default [Connect call failed ('127.0.0.1', 30089)]
[2025-03-07 13:51:41,484] [ERROR] [30076] Error sending to http://localhost:30058/commit: Cannot connect to host localhost:30058 ssl:default [Connect call failed ('::1', 30058, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30058, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30058 ssl:default [Connect call failed ('::1', 30058, 0, 0)]
[2025-03-07 13:51:41,484] [ERROR] [30076] Error sending to http://localhost:30086/commit: Cannot connect to host localhost:30086 ssl:default [Connect call failed ('::1', 30086, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30086, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30086 ssl:default [Connect call failed ('::1', 30086, 0, 0)]
[2025-03-07 13:51:41,484] [ERROR] [30076] Error sending to http://localhost:30062/commit: Cannot connect to host localhost:30062 ssl:default [Connect call failed ('::1', 30062, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30062, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30062 ssl:default [Connect call failed ('::1', 30062, 0, 0)]
[2025-03-07 13:51:41,484] [ERROR] [30076] Error sending to http://localhost:30093/prepare: Cannot connect to host localhost:30093 ssl:default [Connect call failed ('127.0.0.1', 30093)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30093)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30093 ssl:default [Connect call failed ('127.0.0.1', 30093)]
[2025-03-07 13:51:41,484] [ERROR] [30076] Error sending to http://localhost:30089/commit: Cannot connect to host localhost:30089 ssl:default [Connect call failed ('::1', 30089, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30089, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30089 ssl:default [Connect call failed ('::1', 30089, 0, 0)]
[2025-03-07 13:51:41,499] [ERROR] [30076] Error sending to http://localhost:30091/prepare: Cannot connect to host localhost:30091 ssl:default [Connect call failed ('127.0.0.1', 30091)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30091)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30091 ssl:default [Connect call failed ('127.0.0.1', 30091)]
[2025-03-07 13:51:41,502] [INFO] [30076] Received PREPARE: id:1741323095323, from:30034, delay:0.0000s, distance:138.68m (Euclidean)
[2025-03-07 13:51:41,502] [ERROR] [30076] Error sending to http://localhost:30091/commit: Cannot connect to host localhost:30091 ssl:default [Connect call failed ('::1', 30091, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30091, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30091 ssl:default [Connect call failed ('::1', 30091, 0, 0)]
[2025-03-07 13:51:41,531] [ERROR] [30076] Error sending to http://localhost:30085/prepare: Cannot connect to host localhost:30085 ssl:default [Connect call failed ('127.0.0.1', 30085)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30085)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30085 ssl:default [Connect call failed ('127.0.0.1', 30085)]
[2025-03-07 13:51:41,563] [ERROR] [30076] Error sending to http://localhost:30085/commit: Cannot connect to host localhost:30085 ssl:default [Connect call failed ('::1', 30085, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30085, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30085 ssl:default [Connect call failed ('::1', 30085, 0, 0)]
[2025-03-07 13:51:41,579] [ERROR] [30076] Error sending to http://localhost:30087/prepare: Cannot connect to host localhost:30087 ssl:default [Connect call failed ('127.0.0.1', 30087)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30087)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30087 ssl:default [Connect call failed ('127.0.0.1', 30087)]
[2025-03-07 13:51:41,595] [ERROR] [30076] Error sending to http://localhost:30087/commit: Cannot connect to host localhost:30087 ssl:default [Connect call failed ('::1', 30087, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30087, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30087 ssl:default [Connect call failed ('::1', 30087, 0, 0)]
[2025-03-07 13:51:41,642] [INFO] [30076] Received PREPARE: id:1741323095323, from:30059, delay:0.0001s, distance:168.36m (Euclidean)
[2025-03-07 13:51:41,833] [ERROR] [30076] Error sending to http://localhost:30081/prepare: Cannot connect to host localhost:30081 ssl:default [Connect call failed ('127.0.0.1', 30081)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30081)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30081 ssl:default [Connect call failed ('127.0.0.1', 30081)]
[2025-03-07 13:51:41,849] [ERROR] [30076] Error sending to http://localhost:30070/commit: Cannot connect to host localhost:30070 ssl:default [Connect call failed ('::1', 30070, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30070, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30070 ssl:default [Connect call failed ('::1', 30070, 0, 0)]
[2025-03-07 13:51:41,865] [INFO] [30076] Received PREPARE: id:1741323095323, from:30100, delay:0.0001s, distance:196.37m (Euclidean)
[2025-03-07 13:51:41,897] [INFO] [30076] Received COMMIT: id:1741323095323, from:30034, delay:0.0000s, distance:138.68m (Euclidean)
[2025-03-07 13:51:41,907] [INFO] [30076] Received COMMIT: id:1741323095323, from:30059, delay:0.0001s, distance:168.36m (Euclidean)
[2025-03-07 13:51:41,992] [ERROR] [30076] Error sending to http://localhost:30072/commit: Cannot connect to host localhost:30072 ssl:default [Connect call failed ('::1', 30072, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30072, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30072 ssl:default [Connect call failed ('::1', 30072, 0, 0)]
[2025-03-07 13:51:41,992] [ERROR] [30076] Error sending to http://localhost:30072/prepare: Cannot connect to host localhost:30072 ssl:default [Connect call failed ('127.0.0.1', 30072)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30072)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30072 ssl:default [Connect call failed ('127.0.0.1', 30072)]
[2025-03-07 13:51:42,111] [INFO] [30076] Received PREPARE: id:1741323095323, from:30115, delay:0.0000s, distance:121.44m (Euclidean)
[2025-03-07 13:51:42,135] [ERROR] [30076] Error sending to http://localhost:30061/prepare: Cannot connect to host localhost:30061 ssl:default [Connect call failed ('127.0.0.1', 30061)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30061)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30061 ssl:default [Connect call failed ('127.0.0.1', 30061)]
[2025-03-07 13:51:42,150] [ERROR] [30076] Error sending to http://localhost:30061/commit: Cannot connect to host localhost:30061 ssl:default [Connect call failed ('::1', 30061, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30061, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30061 ssl:default [Connect call failed ('::1', 30061, 0, 0)]
[2025-03-07 13:51:42,153] [INFO] [30076] Received PREPARE: id:1741323095323, from:30038, delay:0.0000s, distance:249.25m (Euclidean)
[2025-03-07 13:51:42,170] [INFO] [30076] Received COMMIT: id:1741323095323, from:30100, delay:0.0001s, distance:196.37m (Euclidean)
[2025-03-07 13:51:42,341] [INFO] [30076] Received PREPARE: id:1741323095323, from:30080, delay:0.0002s, distance:254.00m (Euclidean)
[2025-03-07 13:51:42,357] [INFO] [30076] Received COMMIT: id:1741323095323, from:30038, delay:0.0000s, distance:249.25m (Euclidean)
[2025-03-07 13:51:42,389] [INFO] [30076] Received COMMIT: id:1741323095323, from:30115, delay:0.0000s, distance:121.44m (Euclidean)
[2025-03-07 13:51:42,422] [INFO] [30076] Received COMMIT: id:1741323095323, from:30000, delay:0.0000s, distance:106.95m (Euclidean)
[2025-03-07 13:51:42,422] [INFO] [30076] Received PREPARE: id:1741323095323, from:30049, delay:0.0001s, distance:190.54m (Euclidean)
[2025-03-07 13:51:42,468] [INFO] [30076] Received COMMIT: id:1741323095323, from:30049, delay:0.0001s, distance:190.54m (Euclidean)
[2025-03-07 13:51:42,516] [INFO] [30076] Received PREPARE: id:1741323095323, from:30039, delay:0.0000s, distance:111.30m (Euclidean)
[2025-03-07 13:51:42,573] [INFO] [30076] Received COMMIT: id:1741323095323, from:30080, delay:0.0002s, distance:254.00m (Euclidean)
[2025-03-07 13:51:42,580] [INFO] [30076] Received COMMIT: id:1741323095323, from:30039, delay:0.0000s, distance:111.30m (Euclidean)
[2025-03-07 13:51:43,519] [ERROR] [30076] Error sending to http://localhost:30064/commit: Cannot connect to host localhost:30064 ssl:default [Connect call failed ('::1', 30064, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30064, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30064 ssl:default [Connect call failed ('::1', 30064, 0, 0)]
[2025-03-07 13:51:43,519] [ERROR] [30076] Error sending to http://localhost:30063/commit: Cannot connect to host localhost:30063 ssl:default [Connect call failed ('::1', 30063, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30063, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30063 ssl:default [Connect call failed ('::1', 30063, 0, 0)]
[2025-03-07 13:51:43,524] [ERROR] [30076] Error sending to http://localhost:30081/commit: Cannot connect to host localhost:30081 ssl:default [Connect call failed ('::1', 30081, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30081, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30081 ssl:default [Connect call failed ('::1', 30081, 0, 0)]
[2025-03-07 13:51:43,524] [ERROR] [30076] Error sending to http://localhost:30071/prepare: Cannot connect to host localhost:30071 ssl:default [Connect call failed ('127.0.0.1', 30071)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30071)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30071 ssl:default [Connect call failed ('127.0.0.1', 30071)]
[2025-03-07 13:51:43,533] [ERROR] [30076] Error sending to http://localhost:30105/commit: Cannot connect to host localhost:30105 ssl:default [Connect call failed ('::1', 30105, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30105, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30105 ssl:default [Connect call failed ('::1', 30105, 0, 0)]
[2025-03-07 13:51:43,533] [ERROR] [30076] Error sending to http://localhost:30071/commit: Cannot connect to host localhost:30071 ssl:default [Connect call failed ('::1', 30071, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30071, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30071 ssl:default [Connect call failed ('::1', 30071, 0, 0)]
[2025-03-07 13:51:43,533] [ERROR] [30076] Error sending to http://localhost:30073/commit: Cannot connect to host localhost:30073 ssl:default [Connect call failed ('::1', 30073, 0, 0)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('::1', 30073, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30073 ssl:default [Connect call failed ('::1', 30073, 0, 0)]
[2025-03-07 13:51:43,533] [ERROR] [30076] Error sending to http://localhost:30063/prepare: Cannot connect to host localhost:30063 ssl:default [Connect call failed ('127.0.0.1', 30063)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30063)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30063 ssl:default [Connect call failed ('127.0.0.1', 30063)]
[2025-03-07 13:51:43,533] [ERROR] [30076] Error sending to http://localhost:30105/prepare: Cannot connect to host localhost:30105 ssl:default [Connect call failed ('127.0.0.1', 30105)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30105)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30105 ssl:default [Connect call failed ('127.0.0.1', 30105)]
[2025-03-07 13:51:43,533] [ERROR] [30076] Error sending to http://localhost:30073/prepare: Cannot connect to host localhost:30073 ssl:default [Connect call failed ('127.0.0.1', 30073)]
Traceback (most recent call last):
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 948, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\PBFT\lib\asyncio\base_events.py", line 935, in create_connection
    await self.sock_connect(sock, address)
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\anaconda\envs\PBFT\lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 30073)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pbft.py", line 236, in send_message
    await send_with_delay(self.session, self.node_info, target, url, data, self.bandwidth_data)
  File "pbft.py", line 63, in send_with_delay
    async with session.post(url, json=data) as resp:
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\client.py", line 537, in _request
    req, traces=traces, timeout=real_timeout
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "D:\anaconda\envs\PBFT\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:30073 ssl:default [Connect call failed ('127.0.0.1', 30073)]
[2025-03-07 13:52:29,965] [INFO] Starting node at localhost:30076 | index= 77 | f=1, k=4 | Role: Replica
[2025-03-07 13:57:29,462] [INFO] Starting node at localhost:30076 | index= 77 | f=1, k=4 | Role: Replica
[2025-03-07 13:58:31,858] [INFO] Starting node at localhost:30076 | index= 77 | f=1, k=4 | Role: Replica
[2025-03-07 13:59:02,599] [INFO] [30076] Received PRE-PREPARE: id:1741323542381, from:Leader(30000), delay:0.0000s, distance:148.85m (Euclidean)
[2025-03-07 13:59:02,599] [INFO] [30076] Broadcasting PREPARE for REQUEST 1741323542381
[2025-03-07 13:59:02,611] [INFO] [30076] Not broadcasting to fault node: 30077
[2025-03-07 13:59:02,660] [INFO] [30076] Not broadcasting to fault node: 30184
[2025-03-07 13:59:03,118] [INFO] [30076] Received PREPARE: id:1741323542381, from:30155, delay:0.0001s, distance:224.57m (Euclidean)
[2025-03-07 13:59:03,163] [INFO] [30076] Received PREPARE: id:1741323542381, from:30120, delay:0.0000s, distance:91.18m (Euclidean)
[2025-03-07 13:59:03,163] [INFO] [30076] Broadcasting COMMIT for REQUEST 1741323542381
[2025-03-07 13:59:03,177] [INFO] [30076] Not broadcasting to fault node: 30077
[2025-03-07 13:59:03,209] [INFO] [30076] Not broadcasting to fault node: 30184
[2025-03-07 13:59:03,300] [INFO] [30076] Received PREPARE: id:1741323542381, from:30154, delay:0.0000s, distance:138.95m (Euclidean)
[2025-03-07 13:59:03,327] [INFO] [30076] Received PREPARE: id:1741323542381, from:30182, delay:0.0000s, distance:82.19m (Euclidean)
[2025-03-07 13:59:03,327] [INFO] [30076] Received PREPARE: id:1741323542381, from:30046, delay:0.0000s, distance:89.92m (Euclidean)
[2025-03-07 13:59:03,327] [INFO] [30076] Received PREPARE: id:1741323542381, from:30051, delay:0.0000s, distance:150.87m (Euclidean)
[2025-03-07 13:59:03,446] [INFO] [30076] Received PREPARE: id:1741323542381, from:30041, delay:0.0000s, distance:87.98m (Euclidean)
[2025-03-07 13:59:03,505] [INFO] [30076] Received PREPARE: id:1741323542381, from:30195, delay:0.0000s, distance:54.46m (Euclidean)
[2025-03-07 13:59:03,505] [INFO] [30076] Received PREPARE: id:1741323542381, from:30176, delay:0.0000s, distance:87.44m (Euclidean)
[2025-03-07 13:59:03,639] [INFO] [30076] Received PREPARE: id:1741323542381, from:30144, delay:0.0000s, distance:141.13m (Euclidean)
[2025-03-07 13:59:03,694] [INFO] [30076] Received PREPARE: id:1741323542381, from:30189, delay:0.0000s, distance:55.22m (Euclidean)
[2025-03-07 13:59:03,714] [INFO] [30076] Received PREPARE: id:1741323542381, from:30023, delay:0.0000s, distance:124.49m (Euclidean)
[2025-03-07 13:59:03,734] [INFO] [30076] Received PREPARE: id:1741323542381, from:30028, delay:0.0000s, distance:66.93m (Euclidean)
[2025-03-07 13:59:03,734] [INFO] [30076] Received PREPARE: id:1741323542381, from:30005, delay:0.0000s, distance:73.33m (Euclidean)
[2025-03-07 13:59:03,734] [INFO] [30076] Received COMMIT: id:1741323542381, from:30182, delay:0.0000s, distance:82.19m (Euclidean)
[2025-03-07 13:59:04,093] [INFO] [30076] Received PREPARE: id:1741323542381, from:30065, delay:0.0000s, distance:67.04m (Euclidean)
[2025-03-07 13:59:04,229] [INFO] [30076] Received PREPARE: id:1741323542381, from:30179, delay:0.0001s, distance:172.10m (Euclidean)
[2025-03-07 13:59:04,229] [INFO] [30076] Received PREPARE: id:1741323542381, from:30157, delay:0.0001s, distance:161.54m (Euclidean)
[2025-03-07 13:59:04,243] [INFO] [30076] Received PREPARE: id:1741323542381, from:30007, delay:0.0000s, distance:99.50m (Euclidean)
[2025-03-07 13:59:04,318] [INFO] [30076] Received PREPARE: id:1741323542381, from:30108, delay:0.0000s, distance:101.80m (Euclidean)
[2025-03-07 13:59:04,473] [INFO] [30076] Received COMMIT: id:1741323542381, from:30154, delay:0.0000s, distance:138.95m (Euclidean)
[2025-03-07 13:59:04,475] [INFO] [LEADER 30076] Sending REPLY for REQUEST 1741323542381 to CLIENT
[2025-03-07 13:59:04,475] [INFO] [30076] Received PREPARE: id:1741323542381, from:30168, delay:0.0000s, distance:120.47m (Euclidean)
[2025-03-07 13:59:04,475] [INFO] [30076] Received PREPARE: id:1741323542381, from:30167, delay:0.0001s, distance:202.10m (Euclidean)
[2025-03-07 13:59:04,475] [INFO] [30076] Received PREPARE: id:1741323542381, from:30060, delay:0.0001s, distance:193.40m (Euclidean)
[2025-03-07 13:59:04,477] [INFO] [30076] Received PREPARE: id:1741323542381, from:30054, delay:0.0000s, distance:107.47m (Euclidean)
[2025-03-07 13:59:04,477] [INFO] [30076] Received PREPARE: id:1741323542381, from:30112, delay:0.0001s, distance:197.94m (Euclidean)
[2025-03-07 13:59:04,477] [INFO] [30076] Received PREPARE: id:1741323542381, from:30107, delay:0.0001s, distance:190.37m (Euclidean)
[2025-03-07 13:59:04,479] [INFO] [30076] Received COMMIT: id:1741323542381, from:30195, delay:0.0000s, distance:54.46m (Euclidean)
[2025-03-07 13:59:04,479] [INFO] [30076] Received PREPARE: id:1741323542381, from:30070, delay:0.0000s, distance:97.94m (Euclidean)
[2025-03-07 13:59:04,685] [INFO] [30076] Received PREPARE: id:1741323542381, from:30027, delay:0.0000s, distance:76.12m (Euclidean)
[2025-03-07 13:59:04,685] [INFO] [30076] Received COMMIT: id:1741323542381, from:30023, delay:0.0000s, distance:124.49m (Euclidean)
[2025-03-07 13:59:04,857] [INFO] [30076] Received PREPARE: id:1741323542381, from:30119, delay:0.0000s, distance:123.46m (Euclidean)
[2025-03-07 13:59:04,857] [INFO] [30076] Received PREPARE: id:1741323542381, from:30113, delay:0.0000s, distance:131.64m (Euclidean)
[2025-03-07 13:59:04,859] [INFO] [30076] Received PREPARE: id:1741323542381, from:30043, delay:0.0000s, distance:104.01m (Euclidean)
[2025-03-07 13:59:04,859] [INFO] [30076] Received PREPARE: id:1741323542381, from:30130, delay:0.0001s, distance:176.73m (Euclidean)
[2025-03-07 13:59:04,859] [INFO] [30076] Received PREPARE: id:1741323542381, from:30133, delay:0.0001s, distance:212.88m (Euclidean)
[2025-03-07 13:59:04,872] [INFO] [30076] Received PREPARE: id:1741323542381, from:30180, delay:0.0001s, distance:159.52m (Euclidean)
[2025-03-07 13:59:04,875] [INFO] [30076] Received PREPARE: id:1741323542381, from:30149, delay:0.0000s, distance:105.35m (Euclidean)
[2025-03-07 13:59:04,875] [INFO] [30076] Received PREPARE: id:1741323542381, from:30015, delay:0.0000s, distance:118.25m (Euclidean)
[2025-03-07 13:59:04,875] [INFO] [30076] Received PREPARE: id:1741323542381, from:30115, delay:0.0000s, distance:104.86m (Euclidean)
[2025-03-07 13:59:04,875] [INFO] [30076] Received PREPARE: id:1741323542381, from:30129, delay:0.0000s, distance:140.44m (Euclidean)
[2025-03-07 13:59:04,875] [INFO] [30076] Received PREPARE: id:1741323542381, from:30103, delay:0.0000s, distance:146.04m (Euclidean)
[2025-03-07 13:59:04,875] [INFO] [30076] Received COMMIT: id:1741323542381, from:30189, delay:0.0000s, distance:55.22m (Euclidean)
[2025-03-07 13:59:04,875] [INFO] [30076] Received PREPARE: id:1741323542381, from:30121, delay:0.0001s, distance:245.95m (Euclidean)
[2025-03-07 13:59:04,875] [INFO] [30076] Received PREPARE: id:1741323542381, from:30062, delay:0.0001s, distance:171.80m (Euclidean)
[2025-03-07 13:59:04,877] [INFO] [30076] Received PREPARE: id:1741323542381, from:30147, delay:0.0001s, distance:233.02m (Euclidean)
[2025-03-07 13:59:04,877] [INFO] [30076] Received PREPARE: id:1741323542381, from:30106, delay:0.0001s, distance:186.71m (Euclidean)
[2025-03-07 13:59:04,878] [INFO] [30076] Received PREPARE: id:1741323542381, from:30170, delay:0.0001s, distance:225.75m (Euclidean)
[2025-03-07 13:59:04,878] [INFO] [30076] Received PREPARE: id:1741323542381, from:30048, delay:0.0000s, distance:157.24m (Euclidean)
[2025-03-07 13:59:04,879] [INFO] [30076] Received PREPARE: id:1741323542381, from:30109, delay:0.0001s, distance:244.59m (Euclidean)
[2025-03-07 13:59:05,392] [INFO] [30076] Received COMMIT: id:1741323542381, from:30167, delay:0.0001s, distance:202.10m (Euclidean)
[2025-03-07 13:59:05,394] [INFO] [30076] Received COMMIT: id:1741323542381, from:30119, delay:0.0000s, distance:123.46m (Euclidean)
[2025-03-07 13:59:05,394] [INFO] [30076] Received COMMIT: id:1741323542381, from:30133, delay:0.0001s, distance:212.88m (Euclidean)
[2025-03-07 13:59:05,394] [INFO] [30076] Received COMMIT: id:1741323542381, from:30106, delay:0.0001s, distance:186.71m (Euclidean)
[2025-03-07 13:59:05,394] [INFO] [30076] Received COMMIT: id:1741323542381, from:30130, delay:0.0001s, distance:176.73m (Euclidean)
[2025-03-07 13:59:05,396] [INFO] [30076] Received COMMIT: id:1741323542381, from:30113, delay:0.0000s, distance:131.64m (Euclidean)
[2025-03-07 13:59:05,398] [INFO] [30076] Received COMMIT: id:1741323542381, from:30121, delay:0.0001s, distance:245.95m (Euclidean)
[2025-03-07 13:59:05,398] [INFO] [30076] Received PREPARE: id:1741323542381, from:30049, delay:0.0000s, distance:85.88m (Euclidean)
[2025-03-07 13:59:05,495] [INFO] [30076] Received PREPARE: id:1741323542381, from:30090, delay:0.0000s, distance:192.82m (Euclidean)
[2025-03-07 13:59:05,495] [INFO] [30076] Received COMMIT: id:1741323542381, from:30168, delay:0.0000s, distance:120.47m (Euclidean)
[2025-03-07 13:59:05,495] [INFO] [30076] Received PREPARE: id:1741323542381, from:30035, delay:0.0000s, distance:79.60m (Euclidean)
[2025-03-07 13:59:05,495] [INFO] [30076] Received PREPARE: id:1741323542381, from:30102, delay:0.0000s, distance:184.75m (Euclidean)
[2025-03-07 13:59:05,495] [INFO] [30076] Received PREPARE: id:1741323542381, from:30080, delay:0.0002s, distance:277.66m (Euclidean)
[2025-03-07 13:59:05,495] [INFO] [30076] Received PREPARE: id:1741323542381, from:30181, delay:0.0000s, distance:99.04m (Euclidean)
[2025-03-07 13:59:05,497] [INFO] [30076] Received PREPARE: id:1741323542381, from:30150, delay:0.0000s, distance:197.03m (Euclidean)
[2025-03-07 13:59:05,497] [INFO] [30076] Received PREPARE: id:1741323542381, from:30118, delay:0.0001s, distance:211.07m (Euclidean)
[2025-03-07 13:59:05,497] [INFO] [30076] Received PREPARE: id:1741323542381, from:30089, delay:0.0000s, distance:143.21m (Euclidean)
[2025-03-07 13:59:05,498] [INFO] [30076] Received PREPARE: id:1741323542381, from:30040, delay:0.0000s, distance:77.05m (Euclidean)
[2025-03-07 13:59:05,498] [INFO] [30076] Received PREPARE: id:1741323542381, from:30123, delay:0.0000s, distance:125.40m (Euclidean)
[2025-03-07 13:59:05,498] [INFO] [30076] Received PREPARE: id:1741323542381, from:30171, delay:0.0000s, distance:126.93m (Euclidean)
[2025-03-07 13:59:05,706] [INFO] [30076] Received PREPARE: id:1741323542381, from:30161, delay:0.0000s, distance:129.79m (Euclidean)
[2025-03-07 13:59:05,706] [INFO] [30076] Received COMMIT: id:1741323542381, from:30171, delay:0.0000s, distance:126.93m (Euclidean)
[2025-03-07 13:59:05,706] [INFO] [30076] Received PREPARE: id:1741323542381, from:30174, delay:0.0000s, distance:13.10m (Euclidean)
[2025-03-07 13:59:05,706] [INFO] [30076] Received COMMIT: id:1741323542381, from:30157, delay:0.0001s, distance:161.54m (Euclidean)
[2025-03-07 13:59:05,706] [INFO] [30076] Received COMMIT: id:1741323542381, from:30115, delay:0.0000s, distance:104.86m (Euclidean)
[2025-03-07 13:59:05,708] [INFO] [30076] Received PREPARE: id:1741323542381, from:30021, delay:0.0000s, distance:170.23m (Euclidean)
[2025-03-07 13:59:05,708] [INFO] [30076] Received COMMIT: id:1741323542381, from:30028, delay:0.0000s, distance:66.93m (Euclidean)
[2025-03-07 13:59:05,708] [INFO] [30076] Received PREPARE: id:1741323542381, from:30029, delay:0.0002s, distance:297.90m (Euclidean)
[2025-03-07 13:59:05,709] [INFO] [30076] Received PREPARE: id:1741323542381, from:30053, delay:0.0000s, distance:102.63m (Euclidean)
[2025-03-07 13:59:05,709] [INFO] [30076] Received COMMIT: id:1741323542381, from:30144, delay:0.0000s, distance:141.13m (Euclidean)
[2025-03-07 13:59:05,709] [INFO] [30076] Received COMMIT: id:1741323542381, from:30107, delay:0.0001s, distance:190.37m (Euclidean)
[2025-03-07 13:59:05,709] [INFO] [30076] Received COMMIT: id:1741323542381, from:30005, delay:0.0000s, distance:73.33m (Euclidean)
[2025-03-07 13:59:05,950] [INFO] [30076] Received PREPARE: id:1741323542381, from:30092, delay:0.0001s, distance:217.59m (Euclidean)
[2025-03-07 13:59:05,950] [INFO] [30076] Received PREPARE: id:1741323542381, from:30024, delay:0.0000s, distance:49.45m (Euclidean)
[2025-03-07 13:59:05,950] [INFO] [30076] Received COMMIT: id:1741323542381, from:30065, delay:0.0000s, distance:67.04m (Euclidean)
[2025-03-07 13:59:05,950] [INFO] [30076] Received COMMIT: id:1741323542381, from:30149, delay:0.0000s, distance:105.35m (Euclidean)
[2025-03-07 13:59:05,952] [INFO] [30076] Received PREPARE: id:1741323542381, from:30020, delay:0.0000s, distance:131.49m (Euclidean)
[2025-03-07 13:59:05,955] [INFO] [30076] Received COMMIT: id:1741323542381, from:30103, delay:0.0000s, distance:146.04m (Euclidean)
[2025-03-07 13:59:06,562] [INFO] [30076] Received COMMIT: id:1741323542381, from:30007, delay:0.0000s, distance:99.50m (Euclidean)
[2025-03-07 13:59:06,562] [INFO] [30076] Received PREPARE: id:1741323542381, from:30056, delay:0.0001s, distance:216.26m (Euclidean)
[2025-03-07 13:59:06,918] [INFO] [30076] Received COMMIT: id:1741323542381, from:30027, delay:0.0000s, distance:76.12m (Euclidean)
[2025-03-07 13:59:06,922] [INFO] [30076] Received COMMIT: id:1741323542381, from:30051, delay:0.0000s, distance:150.87m (Euclidean)
[2025-03-07 13:59:06,922] [INFO] [30076] Received COMMIT: id:1741323542381, from:30180, delay:0.0001s, distance:159.52m (Euclidean)
[2025-03-07 13:59:07,178] [INFO] [30076] Received COMMIT: id:1741323542381, from:30043, delay:0.0000s, distance:104.01m (Euclidean)
[2025-03-07 13:59:07,178] [INFO] [30076] Received PREPARE: id:1741323542381, from:30011, delay:0.0001s, distance:215.45m (Euclidean)
[2025-03-07 13:59:07,178] [INFO] [30076] Received PREPARE: id:1741323542381, from:30059, delay:0.0001s, distance:229.87m (Euclidean)
[2025-03-07 13:59:07,178] [INFO] [30076] Received PREPARE: id:1741323542381, from:30063, delay:0.0001s, distance:217.73m (Euclidean)
[2025-03-07 13:59:07,182] [INFO] [30076] Received PREPARE: id:1741323542381, from:30013, delay:0.0002s, distance:261.55m (Euclidean)
[2025-03-07 13:59:07,182] [INFO] [30076] Received PREPARE: id:1741323542381, from:30074, delay:0.0001s, distance:225.57m (Euclidean)
[2025-03-07 13:59:07,182] [INFO] [30076] Received PREPARE: id:1741323542381, from:30037, delay:0.0002s, distance:272.30m (Euclidean)
[2025-03-07 13:59:07,184] [INFO] [30076] Received COMMIT: id:1741323542381, from:30176, delay:0.0000s, distance:87.44m (Euclidean)
[2025-03-07 13:59:07,187] [INFO] [30076] Received PREPARE: id:1741323542381, from:30191, delay:0.0000s, distance:91.32m (Euclidean)
[2025-03-07 13:59:07,189] [INFO] [30076] Received COMMIT: id:1741323542381, from:30040, delay:0.0000s, distance:77.05m (Euclidean)
[2025-03-07 13:59:07,341] [INFO] [30076] Received COMMIT: id:1741323542381, from:30015, delay:0.0000s, distance:118.25m (Euclidean)
[2025-03-07 13:59:07,341] [INFO] [30076] Received COMMIT: id:1741323542381, from:30060, delay:0.0001s, distance:193.40m (Euclidean)
[2025-03-07 13:59:07,341] [INFO] [30076] Received COMMIT: id:1741323542381, from:30108, delay:0.0000s, distance:101.80m (Euclidean)
[2025-03-07 13:59:07,341] [INFO] [30076] Received COMMIT: id:1741323542381, from:30147, delay:0.0001s, distance:233.02m (Euclidean)
[2025-03-07 13:59:07,341] [INFO] [30076] Received PREPARE: id:1741323542381, from:30177, delay:0.0000s, distance:123.47m (Euclidean)
[2025-03-07 13:59:07,341] [INFO] [30076] Received COMMIT: id:1741323542381, from:30048, delay:0.0000s, distance:157.24m (Euclidean)
[2025-03-07 13:59:07,341] [INFO] [30076] Received COMMIT: id:1741323542381, from:30035, delay:0.0000s, distance:79.60m (Euclidean)
[2025-03-07 13:59:07,341] [INFO] [30076] Received COMMIT: id:1741323542381, from:30155, delay:0.0001s, distance:224.57m (Euclidean)
[2025-03-07 13:59:07,341] [INFO] [30076] Received COMMIT: id:1741323542381, from:30129, delay:0.0000s, distance:140.44m (Euclidean)
[2025-03-07 13:59:07,341] [INFO] [30076] Received COMMIT: id:1741323542381, from:30170, delay:0.0001s, distance:225.75m (Euclidean)
[2025-03-07 13:59:07,341] [INFO] [30076] Received COMMIT: id:1741323542381, from:30123, delay:0.0000s, distance:125.40m (Euclidean)
[2025-03-07 13:59:07,457] [INFO] [30076] Received COMMIT: id:1741323542381, from:30161, delay:0.0000s, distance:129.79m (Euclidean)
[2025-03-07 13:59:07,457] [INFO] [30076] Received COMMIT: id:1741323542381, from:30080, delay:0.0002s, distance:277.66m (Euclidean)
[2025-03-07 13:59:07,457] [INFO] [30076] Received PREPARE: id:1741323542381, from:30178, delay:0.0000s, distance:114.78m (Euclidean)
[2025-03-07 13:59:07,457] [INFO] [30076] Received COMMIT: id:1741323542381, from:30013, delay:0.0002s, distance:261.55m (Euclidean)
[2025-03-07 13:59:07,462] [INFO] [30076] Received PREPARE: id:1741323542381, from:30196, delay:0.0001s, distance:230.75m (Euclidean)
[2025-03-07 13:59:07,462] [INFO] [30076] Received COMMIT: id:1741323542381, from:30004, delay:0.0000s, distance:174.07m (Euclidean)
[2025-03-07 13:59:07,463] [INFO] [30076] Received COMMIT: id:1741323542381, from:30090, delay:0.0000s, distance:192.82m (Euclidean)
[2025-03-07 13:59:07,463] [INFO] [30076] Received COMMIT: id:1741323542381, from:30046, delay:0.0000s, distance:89.92m (Euclidean)
[2025-03-07 13:59:07,465] [INFO] [30076] Received COMMIT: id:1741323542381, from:30024, delay:0.0000s, distance:49.45m (Euclidean)
[2025-03-07 13:59:07,467] [INFO] [30076] Received COMMIT: id:1741323542381, from:30029, delay:0.0002s, distance:297.90m (Euclidean)
[2025-03-07 13:59:07,467] [INFO] [30076] Received PREPARE: id:1741323542381, from:30004, delay:0.0000s, distance:174.07m (Euclidean)
[2025-03-07 13:59:07,467] [INFO] [30076] Received PREPARE: id:1741323542381, from:30128, delay:0.0001s, distance:246.31m (Euclidean)
[2025-03-07 13:59:07,467] [INFO] [30076] Received COMMIT: id:1741323542381, from:30037, delay:0.0002s, distance:272.30m (Euclidean)
[2025-03-07 13:59:07,467] [INFO] [30076] Received COMMIT: id:1741323542381, from:30041, delay:0.0000s, distance:87.98m (Euclidean)
[2025-03-07 13:59:07,467] [INFO] [30076] Received COMMIT: id:1741323542381, from:30020, delay:0.0000s, distance:131.49m (Euclidean)
[2025-03-07 13:59:07,735] [INFO] [30076] Received PREPARE: id:1741323542381, from:30190, delay:0.0002s, distance:267.39m (Euclidean)
[2025-03-07 13:59:07,735] [INFO] [30076] Received COMMIT: id:1741323542381, from:30102, delay:0.0000s, distance:184.75m (Euclidean)
[2025-03-07 13:59:07,735] [INFO] [30076] Received COMMIT: id:1741323542381, from:30128, delay:0.0001s, distance:246.31m (Euclidean)
[2025-03-07 13:59:07,735] [INFO] [30076] Received COMMIT: id:1741323542381, from:30063, delay:0.0001s, distance:217.73m (Euclidean)
[2025-03-07 13:59:07,735] [INFO] [30076] Received COMMIT: id:1741323542381, from:30196, delay:0.0001s, distance:230.75m (Euclidean)
[2025-03-07 13:59:07,735] [INFO] [30076] Received COMMIT: id:1741323542381, from:30053, delay:0.0000s, distance:102.63m (Euclidean)
[2025-03-07 13:59:07,735] [INFO] [30076] Received COMMIT: id:1741323542381, from:30011, delay:0.0001s, distance:215.45m (Euclidean)
[2025-03-07 13:59:07,735] [INFO] [30076] Received COMMIT: id:1741323542381, from:30059, delay:0.0001s, distance:229.87m (Euclidean)
[2025-03-07 13:59:07,739] [INFO] [30076] Received COMMIT: id:1741323542381, from:30118, delay:0.0001s, distance:211.07m (Euclidean)
[2025-03-07 13:59:07,809] [INFO] [30076] Received COMMIT: id:1741323542381, from:30190, delay:0.0002s, distance:267.39m (Euclidean)
[2025-03-07 13:59:07,809] [INFO] [30076] Received PREPARE: id:1741323542381, from:30199, delay:0.0002s, distance:279.97m (Euclidean)
[2025-03-07 13:59:07,809] [INFO] [30076] Received PREPARE: id:1741323542381, from:30093, delay:0.0001s, distance:194.83m (Euclidean)
[2025-03-07 13:59:07,809] [INFO] [30076] Received PREPARE: id:1741323542381, from:30025, delay:0.0001s, distance:229.34m (Euclidean)
[2025-03-07 13:59:07,825] [INFO] [30076] Received COMMIT: id:1741323542381, from:30093, delay:0.0001s, distance:194.83m (Euclidean)
[2025-03-07 13:59:07,825] [INFO] [30076] Received COMMIT: id:1741323542381, from:30025, delay:0.0001s, distance:229.34m (Euclidean)
[2025-03-07 13:59:07,825] [INFO] [30076] Received COMMIT: id:1741323542381, from:30062, delay:0.0001s, distance:171.80m (Euclidean)
[2025-03-07 13:59:07,870] [INFO] [30076] Received PREPARE: id:1741323542381, from:30124, delay:0.0001s, distance:241.47m (Euclidean)
[2025-03-07 13:59:07,870] [INFO] [30076] Received COMMIT: id:1741323542381, from:30179, delay:0.0001s, distance:172.10m (Euclidean)
[2025-03-07 13:59:07,930] [INFO] [30076] Received PREPARE: id:1741323542381, from:30116, delay:0.0001s, distance:225.54m (Euclidean)
[2025-03-07 13:59:07,930] [INFO] [30076] Received COMMIT: id:1741323542381, from:30116, delay:0.0001s, distance:225.54m (Euclidean)
[2025-03-07 13:59:07,935] [INFO] [30076] Received PREPARE: id:1741323542381, from:30175, delay:0.0000s, distance:178.34m (Euclidean)
[2025-03-07 13:59:07,935] [INFO] [30076] Received COMMIT: id:1741323542381, from:30054, delay:0.0000s, distance:107.47m (Euclidean)
[2025-03-07 13:59:08,109] [INFO] [30076] Received COMMIT: id:1741323542381, from:30070, delay:0.0000s, distance:97.94m (Euclidean)
[2025-03-07 13:59:08,380] [INFO] [30076] Received COMMIT: id:1741323542381, from:30177, delay:0.0000s, distance:123.47m (Euclidean)
[2025-03-07 13:59:08,380] [INFO] [30076] Received COMMIT: id:1741323542381, from:30074, delay:0.0001s, distance:225.57m (Euclidean)
[2025-03-07 13:59:08,427] [INFO] [30076] Received COMMIT: id:1741323542381, from:30175, delay:0.0000s, distance:178.34m (Euclidean)
[2025-03-07 13:59:08,429] [INFO] [30076] Received COMMIT: id:1741323542381, from:30150, delay:0.0000s, distance:197.03m (Euclidean)
[2025-03-07 13:59:08,515] [INFO] [30076] Received COMMIT: id:1741323542381, from:30092, delay:0.0001s, distance:217.59m (Euclidean)
[2025-03-07 13:59:08,515] [INFO] [30076] Received COMMIT: id:1741323542381, from:30178, delay:0.0000s, distance:114.78m (Euclidean)
[2025-03-07 13:59:08,515] [INFO] [30076] Received PREPARE: id:1741323542381, from:30136, delay:0.0001s, distance:163.03m (Euclidean)
[2025-03-07 13:59:08,517] [INFO] [30076] Received COMMIT: id:1741323542381, from:30181, delay:0.0000s, distance:99.04m (Euclidean)
[2025-03-07 13:59:08,517] [INFO] [30076] Received COMMIT: id:1741323542381, from:30089, delay:0.0000s, distance:143.21m (Euclidean)
[2025-03-07 13:59:08,517] [INFO] [30076] Received COMMIT: id:1741323542381, from:30021, delay:0.0000s, distance:170.23m (Euclidean)
[2025-03-07 13:59:08,517] [INFO] [30076] Received COMMIT: id:1741323542381, from:30199, delay:0.0002s, distance:279.97m (Euclidean)
[2025-03-07 13:59:08,697] [INFO] [30076] Received COMMIT: id:1741323542381, from:30169, delay:0.0002s, distance:279.10m (Euclidean)
[2025-03-07 13:59:08,697] [INFO] [30076] Received COMMIT: id:1741323542381, from:30191, delay:0.0000s, distance:91.32m (Euclidean)
[2025-03-07 13:59:08,697] [INFO] [30076] Received PREPARE: id:1741323542381, from:30085, delay:0.0001s, distance:213.98m (Euclidean)
[2025-03-07 13:59:08,697] [INFO] [30076] Received COMMIT: id:1741323542381, from:30136, delay:0.0001s, distance:163.03m (Euclidean)
[2025-03-07 13:59:08,697] [INFO] [30076] Received COMMIT: id:1741323542381, from:30085, delay:0.0001s, distance:213.98m (Euclidean)
[2025-03-07 13:59:08,697] [INFO] [30076] Received COMMIT: id:1741323542381, from:30174, delay:0.0000s, distance:13.10m (Euclidean)
[2025-03-07 13:59:08,697] [INFO] [30076] Received PREPARE: id:1741323542381, from:30169, delay:0.0002s, distance:279.10m (Euclidean)
[2025-03-07 13:59:08,697] [INFO] [30076] Received PREPARE: id:1741323542381, from:30110, delay:0.0001s, distance:230.54m (Euclidean)
[2025-03-07 13:59:08,697] [INFO] [30076] Received COMMIT: id:1741323542381, from:30110, delay:0.0001s, distance:230.54m (Euclidean)
[2025-03-07 13:59:08,697] [INFO] [30076] Received COMMIT: id:1741323542381, from:30109, delay:0.0001s, distance:244.59m (Euclidean)
[2025-03-07 13:59:08,760] [INFO] [30076] Received PREPARE: id:1741323542381, from:30057, delay:0.0001s, distance:194.12m (Euclidean)
[2025-03-07 13:59:08,771] [INFO] [30076] Received COMMIT: id:1741323542381, from:30049, delay:0.0000s, distance:85.88m (Euclidean)
[2025-03-07 13:59:08,771] [INFO] [30076] Received COMMIT: id:1741323542381, from:30056, delay:0.0001s, distance:216.26m (Euclidean)
[2025-03-07 13:59:08,771] [INFO] [30076] Received COMMIT: id:1741323542381, from:30096, delay:0.0001s, distance:244.44m (Euclidean)
[2025-03-07 13:59:08,771] [INFO] [30076] Received PREPARE: id:1741323542381, from:30096, delay:0.0001s, distance:244.44m (Euclidean)
[2025-03-07 13:59:08,812] [INFO] [30076] Received COMMIT: id:1741323542381, from:30057, delay:0.0001s, distance:194.12m (Euclidean)
[2025-03-07 13:59:08,812] [INFO] [30076] Received COMMIT: id:1741323542381, from:30112, delay:0.0001s, distance:197.94m (Euclidean)
[2025-03-07 13:59:08,922] [INFO] [30076] Received COMMIT: id:1741323542381, from:30120, delay:0.0000s, distance:91.18m (Euclidean)
[2025-03-07 13:59:08,937] [INFO] [30076] Received PREPARE: id:1741323542381, from:30111, delay:0.0000s, distance:182.37m (Euclidean)
[2025-03-07 13:59:08,939] [INFO] [30076] Received COMMIT: id:1741323542381, from:30111, delay:0.0000s, distance:182.37m (Euclidean)
[2025-03-07 13:59:09,004] [INFO] [30076] Received COMMIT: id:1741323542381, from:30124, delay:0.0001s, distance:241.47m (Euclidean)
[2025-03-07 13:59:09,022] [INFO] [30076] Received PREPARE: id:1741323542381, from:30158, delay:0.0001s, distance:235.53m (Euclidean)
[2025-03-07 13:59:09,108] [INFO] [30076] Received PREPARE: id:1741323542381, from:30126, delay:0.0002s, distance:259.91m (Euclidean)
[2025-03-07 13:59:09,122] [INFO] [30076] Received COMMIT: id:1741323542381, from:30126, delay:0.0002s, distance:259.91m (Euclidean)
[2025-03-07 13:59:09,517] [INFO] [30076] Received COMMIT: id:1741323542381, from:30158, delay:0.0001s, distance:235.53m (Euclidean)
[2025-03-07 13:59:09,768] [INFO] [30076] Received PREPARE: id:1741323542381, from:30098, delay:0.0001s, distance:235.58m (Euclidean)
[2025-03-07 13:59:09,768] [INFO] [30076] Received COMMIT: id:1741323542381, from:30098, delay:0.0001s, distance:235.58m (Euclidean)
[2025-03-07 13:59:09,982] [INFO] [30076] Received PREPARE: id:1741323542381, from:30066, delay:0.0001s, distance:208.12m (Euclidean)
[2025-03-07 13:59:09,982] [INFO] [30076] Received PREPARE: id:1741323542381, from:30127, delay:0.0001s, distance:167.75m (Euclidean)
[2025-03-07 13:59:09,984] [INFO] [30076] Received COMMIT: id:1741323542381, from:30127, delay:0.0001s, distance:167.75m (Euclidean)
[2025-03-07 13:59:09,984] [INFO] [30076] Received COMMIT: id:1741323542381, from:30066, delay:0.0001s, distance:208.12m (Euclidean)
[2025-03-07 13:59:10,817] [INFO] [30076] Received PREPARE: id:1741323542381, from:30100, delay:0.0001s, distance:244.53m (Euclidean)
[2025-03-07 13:59:10,820] [INFO] [30076] Received COMMIT: id:1741323542381, from:30100, delay:0.0001s, distance:244.53m (Euclidean)
[2025-03-07 13:59:10,934] [INFO] [30076] Received PREPARE: id:1741323542381, from:30034, delay:0.0000s, distance:147.04m (Euclidean)
[2025-03-07 13:59:11,585] [INFO] [30076] Received PREPARE: id:1741323542381, from:30016, delay:0.0000s, distance:150.99m (Euclidean)
[2025-03-07 13:59:11,645] [INFO] [30076] Received PREPARE: id:1741323542381, from:30095, delay:0.0001s, distance:241.79m (Euclidean)
[2025-03-07 13:59:11,665] [INFO] [30076] Received COMMIT: id:1741323542381, from:30095, delay:0.0001s, distance:241.79m (Euclidean)
[2025-03-07 13:59:12,512] [INFO] [30076] Received PREPARE: id:1741323542381, from:30081, delay:0.0000s, distance:34.10m (Euclidean)
[2025-03-07 13:59:12,817] [INFO] [30076] Received PREPARE: id:1741323542381, from:30194, delay:0.0000s, distance:120.60m (Euclidean)
[2025-03-07 13:59:12,817] [INFO] [30076] Received COMMIT: id:1741323542381, from:30194, delay:0.0000s, distance:120.60m (Euclidean)
[2025-03-07 13:59:12,848] [INFO] [30076] Received PREPARE: id:1741323542381, from:30134, delay:0.0000s, distance:107.90m (Euclidean)
[2025-03-07 13:59:12,926] [INFO] [30076] Received PREPARE: id:1741323542381, from:30026, delay:0.0000s, distance:112.85m (Euclidean)
[2025-03-07 13:59:12,974] [INFO] [30076] Received PREPARE: id:1741323542381, from:30068, delay:0.0000s, distance:200.38m (Euclidean)
[2025-03-07 13:59:13,000] [INFO] [30076] Received COMMIT: id:1741323542381, from:30081, delay:0.0000s, distance:34.10m (Euclidean)
[2025-03-07 13:59:13,166] [INFO] [30076] Received COMMIT: id:1741323542381, from:30134, delay:0.0000s, distance:107.90m (Euclidean)
[2025-03-07 13:59:13,332] [INFO] [30076] Received PREPARE: id:1741323542381, from:30125, delay:0.0002s, distance:283.24m (Euclidean)
[2025-03-07 13:59:13,332] [INFO] [30076] Received PREPARE: id:1741323542381, from:30061, delay:0.0001s, distance:172.38m (Euclidean)
[2025-03-07 13:59:13,332] [INFO] [30076] Received COMMIT: id:1741323542381, from:30125, delay:0.0002s, distance:283.24m (Euclidean)
[2025-03-07 13:59:13,386] [INFO] [30076] Received COMMIT: id:1741323542381, from:30000, delay:0.0000s, distance:148.85m (Euclidean)
[2025-03-07 13:59:13,421] [INFO] [30076] Received COMMIT: id:1741323542381, from:30061, delay:0.0001s, distance:172.38m (Euclidean)
[2025-03-07 13:59:13,569] [INFO] [30076] Received PREPARE: id:1741323542381, from:30198, delay:0.0000s, distance:143.98m (Euclidean)
[2025-03-07 13:59:13,664] [INFO] [30076] Received PREPARE: id:1741323542381, from:30064, delay:0.0000s, distance:132.22m (Euclidean)
[2025-03-07 13:59:13,828] [INFO] [30076] Received COMMIT: id:1741323542381, from:30026, delay:0.0000s, distance:112.85m (Euclidean)
[2025-03-07 13:59:13,866] [INFO] [30076] Received PREPARE: id:1741323542381, from:30031, delay:0.0001s, distance:245.37m (Euclidean)
[2025-03-07 13:59:13,903] [INFO] [30076] Received COMMIT: id:1741323542381, from:30016, delay:0.0000s, distance:150.99m (Euclidean)
[2025-03-07 13:59:13,942] [INFO] [30076] Received PREPARE: id:1741323542381, from:30160, delay:0.0000s, distance:131.66m (Euclidean)
[2025-03-07 13:59:13,942] [INFO] [30076] Received COMMIT: id:1741323542381, from:30160, delay:0.0000s, distance:131.66m (Euclidean)
[2025-03-07 13:59:13,976] [INFO] [30076] Received PREPARE: id:1741323542381, from:30067, delay:0.0002s, distance:294.87m (Euclidean)
[2025-03-07 13:59:13,982] [INFO] [30076] Received COMMIT: id:1741323542381, from:30067, delay:0.0002s, distance:294.87m (Euclidean)
[2025-03-07 13:59:14,035] [INFO] [30076] Received PREPARE: id:1741323542381, from:30114, delay:0.0002s, distance:274.72m (Euclidean)
[2025-03-07 13:59:14,037] [INFO] [30076] Received COMMIT: id:1741323542381, from:30114, delay:0.0002s, distance:274.72m (Euclidean)
[2025-03-07 13:59:14,122] [INFO] [30076] Received PREPARE: id:1741323542381, from:30086, delay:0.0001s, distance:207.08m (Euclidean)
[2025-03-07 13:59:14,122] [INFO] [30076] Received COMMIT: id:1741323542381, from:30086, delay:0.0001s, distance:207.08m (Euclidean)
[2025-03-07 13:59:14,144] [INFO] [30076] Received PREPARE: id:1741323542381, from:30019, delay:0.0001s, distance:221.89m (Euclidean)
[2025-03-07 13:59:14,144] [INFO] [30076] Received COMMIT: id:1741323542381, from:30019, delay:0.0001s, distance:221.89m (Euclidean)
[2025-03-07 13:59:14,222] [INFO] [30076] Received PREPARE: id:1741323542381, from:30079, delay:0.0002s, distance:290.23m (Euclidean)
[2025-03-07 13:59:14,222] [INFO] [30076] Received COMMIT: id:1741323542381, from:30079, delay:0.0002s, distance:290.23m (Euclidean)
[2025-03-07 13:59:14,574] [INFO] [30076] Received PREPARE: id:1741323542381, from:30010, delay:0.0001s, distance:166.14m (Euclidean)
[2025-03-07 13:59:14,574] [INFO] [30076] Received COMMIT: id:1741323542381, from:30010, delay:0.0001s, distance:166.14m (Euclidean)
[2025-03-07 13:59:14,791] [INFO] [30076] Received PREPARE: id:1741323542381, from:30141, delay:0.0000s, distance:54.09m (Euclidean)
[2025-03-07 13:59:14,793] [INFO] [30076] Received COMMIT: id:1741323542381, from:30141, delay:0.0000s, distance:54.09m (Euclidean)
[2025-03-07 13:59:14,799] [INFO] [30076] Received PREPARE: id:1741323542381, from:30197, delay:0.0002s, distance:263.77m (Euclidean)
[2025-03-07 13:59:14,934] [INFO] [30076] Received PREPARE: id:1741323542381, from:30137, delay:0.0001s, distance:165.15m (Euclidean)
[2025-03-07 13:59:14,936] [INFO] [30076] Received COMMIT: id:1741323542381, from:30137, delay:0.0001s, distance:165.15m (Euclidean)
[2025-03-07 13:59:14,977] [INFO] [30076] Received PREPARE: id:1741323542381, from:30117, delay:0.0001s, distance:153.40m (Euclidean)
[2025-03-07 13:59:14,977] [INFO] [30076] Received COMMIT: id:1741323542381, from:30117, delay:0.0001s, distance:153.40m (Euclidean)
[2025-03-07 13:59:15,005] [INFO] [30076] Received PREPARE: id:1741323542381, from:30058, delay:0.0002s, distance:252.45m (Euclidean)
[2025-03-07 13:59:15,005] [INFO] [30076] Received COMMIT: id:1741323542381, from:30058, delay:0.0002s, distance:252.45m (Euclidean)
[2025-03-07 13:59:15,065] [INFO] [30076] Received PREPARE: id:1741323542381, from:30094, delay:0.0001s, distance:245.63m (Euclidean)
[2025-03-07 13:59:15,065] [INFO] [30076] Received COMMIT: id:1741323542381, from:30094, delay:0.0001s, distance:245.63m (Euclidean)
[2025-03-07 13:59:15,065] [INFO] [30076] Received PREPARE: id:1741323542381, from:30055, delay:0.0000s, distance:141.08m (Euclidean)
[2025-03-07 13:59:15,065] [INFO] [30076] Received COMMIT: id:1741323542381, from:30055, delay:0.0000s, distance:141.08m (Euclidean)
[2025-03-07 13:59:15,207] [INFO] [30076] Received PREPARE: id:1741323542381, from:30156, delay:0.0000s, distance:134.28m (Euclidean)
[2025-03-07 13:59:15,209] [INFO] [30076] Received PREPARE: id:1741323542381, from:30153, delay:0.0001s, distance:177.16m (Euclidean)
[2025-03-07 13:59:15,290] [INFO] [30076] Received PREPARE: id:1741323542381, from:30083, delay:0.0000s, distance:107.61m (Euclidean)
[2025-03-07 13:59:15,331] [INFO] [30076] Received PREPARE: id:1741323542381, from:30143, delay:0.0001s, distance:235.96m (Euclidean)
[2025-03-07 13:59:15,337] [INFO] [30076] Received PREPARE: id:1741323542381, from:30050, delay:0.0002s, distance:251.67m (Euclidean)
[2025-03-07 13:59:15,415] [INFO] [30076] Received COMMIT: id:1741323542381, from:30068, delay:0.0000s, distance:200.38m (Euclidean)
[2025-03-07 13:59:15,465] [INFO] [30076] Received PREPARE: id:1741323542381, from:30069, delay:0.0001s, distance:245.17m (Euclidean)
[2025-03-07 13:59:15,651] [INFO] [30076] Received COMMIT: id:1741323542381, from:30064, delay:0.0000s, distance:132.22m (Euclidean)
[2025-03-07 13:59:15,729] [INFO] [30076] Received COMMIT: id:1741323542381, from:30050, delay:0.0002s, distance:251.67m (Euclidean)
[2025-03-07 13:59:15,740] [INFO] [30076] Received COMMIT: id:1741323542381, from:30034, delay:0.0000s, distance:147.04m (Euclidean)
[2025-03-07 13:59:15,792] [INFO] [30076] Received COMMIT: id:1741323542381, from:30069, delay:0.0001s, distance:245.17m (Euclidean)
[2025-03-07 13:59:15,795] [INFO] [30076] Received PREPARE: id:1741323542381, from:30186, delay:0.0000s, distance:109.05m (Euclidean)
[2025-03-07 13:59:15,998] [INFO] [30076] Received PREPARE: id:1741323542381, from:30039, delay:0.0001s, distance:241.52m (Euclidean)
[2025-03-07 13:59:16,283] [INFO] [30076] Received PREPARE: id:1741323542381, from:30138, delay:0.0002s, distance:254.82m (Euclidean)
[2025-03-07 13:59:16,306] [INFO] [30076] Received PREPARE: id:1741323542381, from:30159, delay:0.0000s, distance:111.54m (Euclidean)
[2025-03-07 13:59:16,306] [INFO] [30076] Received COMMIT: id:1741323542381, from:30159, delay:0.0000s, distance:111.54m (Euclidean)
[2025-03-07 13:59:16,481] [INFO] [30076] Received PREPARE: id:1741323542381, from:30104, delay:0.0001s, distance:173.57m (Euclidean)
[2025-03-07 13:59:16,544] [INFO] [30076] Received COMMIT: id:1741323542381, from:30153, delay:0.0001s, distance:177.16m (Euclidean)
[2025-03-07 13:59:16,692] [INFO] [30076] Received PREPARE: id:1741323542381, from:30101, delay:0.0000s, distance:34.96m (Euclidean)
[2025-03-07 13:59:16,733] [INFO] [30076] Received COMMIT: id:1741323542381, from:30138, delay:0.0002s, distance:254.82m (Euclidean)
[2025-03-07 13:59:16,892] [INFO] [30076] Received COMMIT: id:1741323542381, from:30156, delay:0.0000s, distance:134.28m (Euclidean)
[2025-03-07 13:59:17,026] [INFO] [30076] Received PREPARE: id:1741323542381, from:30105, delay:0.0001s, distance:206.28m (Euclidean)
[2025-03-07 13:59:17,093] [INFO] [30076] Received PREPARE: id:1741323542381, from:30193, delay:0.0001s, distance:247.89m (Euclidean)
[2025-03-07 13:59:17,095] [INFO] [30076] Received COMMIT: id:1741323542381, from:30193, delay:0.0001s, distance:247.89m (Euclidean)
[2025-03-07 13:59:17,101] [INFO] [30076] Received PREPARE: id:1741323542381, from:30131, delay:0.0002s, distance:263.86m (Euclidean)
[2025-03-07 13:59:17,126] [INFO] [30076] Received COMMIT: id:1741323542381, from:30039, delay:0.0001s, distance:241.52m (Euclidean)
[2025-03-07 13:59:17,217] [INFO] [30076] Received COMMIT: id:1741323542381, from:30198, delay:0.0000s, distance:143.98m (Euclidean)
[2025-03-07 13:59:17,246] [INFO] [30076] Received PREPARE: id:1741323542381, from:30091, delay:0.0001s, distance:228.52m (Euclidean)
[2025-03-07 13:59:17,248] [INFO] [30076] Received COMMIT: id:1741323542381, from:30091, delay:0.0001s, distance:228.52m (Euclidean)
[2025-03-07 13:59:17,311] [INFO] [30076] Received PREPARE: id:1741323542381, from:30173, delay:0.0001s, distance:237.59m (Euclidean)
[2025-03-07 13:59:17,311] [INFO] [30076] Received COMMIT: id:1741323542381, from:30173, delay:0.0001s, distance:237.59m (Euclidean)
[2025-03-07 13:59:17,415] [INFO] [30076] Received COMMIT: id:1741323542381, from:30104, delay:0.0001s, distance:173.57m (Euclidean)
[2025-03-07 13:59:17,458] [INFO] [30076] Received PREPARE: id:1741323542381, from:30042, delay:0.0001s, distance:221.09m (Euclidean)
[2025-03-07 13:59:17,683] [INFO] [30076] Received COMMIT: id:1741323542381, from:30031, delay:0.0001s, distance:245.37m (Euclidean)
[2025-03-07 13:59:17,783] [INFO] [30076] Received COMMIT: id:1741323542381, from:30197, delay:0.0002s, distance:263.77m (Euclidean)
[2025-03-07 13:59:17,785] [INFO] [30076] Received PREPARE: id:1741323542381, from:30165, delay:0.0002s, distance:262.80m (Euclidean)
[2025-03-07 13:59:17,790] [INFO] [30076] Received COMMIT: id:1741323542381, from:30143, delay:0.0001s, distance:235.96m (Euclidean)
[2025-03-07 13:59:17,792] [INFO] [30076] Received COMMIT: id:1741323542381, from:30165, delay:0.0002s, distance:262.80m (Euclidean)
[2025-03-07 13:59:17,996] [INFO] [30076] Received PREPARE: id:1741323542381, from:30122, delay:0.0002s, distance:281.06m (Euclidean)
[2025-03-07 13:59:18,166] [INFO] [30076] Received PREPARE: id:1741323542381, from:30099, delay:0.0001s, distance:174.13m (Euclidean)
[2025-03-07 13:59:18,211] [INFO] [30076] Received PREPARE: id:1741323542381, from:30088, delay:0.0002s, distance:297.98m (Euclidean)
[2025-03-07 13:59:18,211] [INFO] [30076] Received COMMIT: id:1741323542381, from:30088, delay:0.0002s, distance:297.98m (Euclidean)
[2025-03-07 13:59:18,241] [INFO] [30076] Received COMMIT: id:1741323542381, from:30101, delay:0.0000s, distance:34.96m (Euclidean)
[2025-03-07 13:59:18,243] [INFO] [30076] Received COMMIT: id:1741323542381, from:30122, delay:0.0002s, distance:281.06m (Euclidean)
[2025-03-07 13:59:18,268] [INFO] [30076] Received PREPARE: id:1741323542381, from:30045, delay:0.0001s, distance:224.26m (Euclidean)
[2025-03-07 13:59:18,670] [INFO] [30076] Received COMMIT: id:1741323542381, from:30105, delay:0.0001s, distance:206.28m (Euclidean)
[2025-03-07 13:59:18,789] [INFO] [30076] Received PREPARE: id:1741323542381, from:30008, delay:0.0000s, distance:171.10m (Euclidean)
[2025-03-07 13:59:18,853] [INFO] [30076] Received PREPARE: id:1741323542381, from:30084, delay:0.0002s, distance:281.80m (Euclidean)
[2025-03-07 13:59:18,855] [INFO] [30076] Received COMMIT: id:1741323542381, from:30084, delay:0.0002s, distance:281.80m (Euclidean)
[2025-03-07 13:59:18,880] [INFO] [30076] Received COMMIT: id:1741323542381, from:30131, delay:0.0002s, distance:263.86m (Euclidean)
[2025-03-07 13:59:19,329] [INFO] [30076] Received COMMIT: id:1741323542381, from:30045, delay:0.0001s, distance:224.26m (Euclidean)
[2025-03-07 13:59:19,329] [INFO] [30076] Received PREPARE: id:1741323542381, from:30140, delay:0.0001s, distance:236.57m (Euclidean)
[2025-03-07 13:59:19,329] [INFO] [30076] Received COMMIT: id:1741323542381, from:30140, delay:0.0001s, distance:236.57m (Euclidean)
[2025-03-07 13:59:19,498] [INFO] [30076] Received PREPARE: id:1741323542381, from:30052, delay:0.0002s, distance:264.62m (Euclidean)
[2025-03-07 13:59:19,499] [INFO] [30076] Received COMMIT: id:1741323542381, from:30052, delay:0.0002s, distance:264.62m (Euclidean)
[2025-03-07 13:59:19,585] [INFO] [30076] Received PREPARE: id:1741323542381, from:30022, delay:0.0001s, distance:210.57m (Euclidean)
[2025-03-07 13:59:19,587] [INFO] [30076] Received COMMIT: id:1741323542381, from:30022, delay:0.0001s, distance:210.57m (Euclidean)
[2025-03-07 13:59:19,665] [INFO] [30076] Received PREPARE: id:1741323542381, from:30003, delay:0.0002s, distance:255.39m (Euclidean)
[2025-03-07 13:59:19,665] [INFO] [30076] Received COMMIT: id:1741323542381, from:30003, delay:0.0002s, distance:255.39m (Euclidean)
[2025-03-07 13:59:19,803] [INFO] [30076] Received COMMIT: id:1741323542381, from:30083, delay:0.0000s, distance:107.61m (Euclidean)
[2025-03-07 13:59:19,855] [INFO] [30076] Received PREPARE: id:1741323542381, from:30162, delay:0.0002s, distance:266.31m (Euclidean)
[2025-03-07 13:59:19,855] [INFO] [30076] Received COMMIT: id:1741323542381, from:30162, delay:0.0002s, distance:266.31m (Euclidean)
[2025-03-07 13:59:20,250] [INFO] [30076] Received PREPARE: id:1741323542381, from:30132, delay:0.0001s, distance:212.79m (Euclidean)
[2025-03-07 13:59:20,250] [INFO] [30076] Received COMMIT: id:1741323542381, from:30132, delay:0.0001s, distance:212.79m (Euclidean)
[2025-03-07 13:59:20,428] [INFO] [30076] Received COMMIT: id:1741323542381, from:30042, delay:0.0001s, distance:221.09m (Euclidean)
[2025-03-07 13:59:21,292] [INFO] [30076] Received PREPARE: id:1741323542381, from:30036, delay:0.0002s, distance:267.47m (Euclidean)
[2025-03-07 13:59:21,292] [INFO] [30076] Received COMMIT: id:1741323542381, from:30036, delay:0.0002s, distance:267.47m (Euclidean)
[2025-03-07 13:59:21,397] [INFO] [30076] Received PREPARE: id:1741323542381, from:30187, delay:0.0001s, distance:246.45m (Euclidean)
[2025-03-07 13:59:21,397] [INFO] [30076] Received COMMIT: id:1741323542381, from:30187, delay:0.0001s, distance:246.45m (Euclidean)
[2025-03-07 13:59:21,471] [INFO] [30076] Received PREPARE: id:1741323542381, from:30188, delay:0.0002s, distance:253.56m (Euclidean)
[2025-03-07 13:59:21,480] [INFO] [30076] Received COMMIT: id:1741323542381, from:30188, delay:0.0002s, distance:253.56m (Euclidean)
[2025-03-07 13:59:22,195] [INFO] [30076] Received COMMIT: id:1741323542381, from:30186, delay:0.0000s, distance:109.05m (Euclidean)
[2025-03-07 13:59:22,338] [INFO] [30076] Received PREPARE: id:1741323542381, from:30071, delay:0.0002s, distance:274.74m (Euclidean)
[2025-03-07 13:59:22,338] [INFO] [30076] Received COMMIT: id:1741323542381, from:30071, delay:0.0002s, distance:274.74m (Euclidean)
[2025-03-07 13:59:22,380] [INFO] [30076] Received PREPARE: id:1741323542381, from:30017, delay:0.0002s, distance:251.93m (Euclidean)
[2025-03-07 13:59:22,380] [INFO] [30076] Received COMMIT: id:1741323542381, from:30017, delay:0.0002s, distance:251.93m (Euclidean)
[2025-03-07 13:59:22,573] [INFO] [30076] Received PREPARE: id:1741323542381, from:30139, delay:0.0001s, distance:236.17m (Euclidean)
[2025-03-07 13:59:22,573] [INFO] [30076] Received COMMIT: id:1741323542381, from:30139, delay:0.0001s, distance:236.17m (Euclidean)
[2025-03-07 13:59:22,876] [INFO] [30076] Received PREPARE: id:1741323542381, from:30009, delay:0.0001s, distance:159.71m (Euclidean)
[2025-03-07 13:59:22,912] [INFO] [30076] Received PREPARE: id:1741323542381, from:30001, delay:0.0002s, distance:263.10m (Euclidean)
[2025-03-07 13:59:22,920] [INFO] [30076] Received COMMIT: id:1741323542381, from:30001, delay:0.0002s, distance:263.10m (Euclidean)
[2025-03-07 13:59:22,949] [INFO] [30076] Received COMMIT: id:1741323542381, from:30008, delay:0.0000s, distance:171.10m (Euclidean)
[2025-03-07 13:59:23,268] [INFO] [30076] Received PREPARE: id:1741323542381, from:30166, delay:0.0002s, distance:257.91m (Euclidean)
[2025-03-07 13:59:23,282] [INFO] [30076] Received COMMIT: id:1741323542381, from:30166, delay:0.0002s, distance:257.91m (Euclidean)
[2025-03-07 13:59:23,465] [INFO] [30076] Received PREPARE: id:1741323542381, from:30044, delay:0.0000s, distance:249.29m (Euclidean)
[2025-03-07 13:59:23,487] [INFO] [30076] Received PREPARE: id:1741323542381, from:30038, delay:0.0001s, distance:173.02m (Euclidean)
[2025-03-07 13:59:23,489] [INFO] [30076] Received COMMIT: id:1741323542381, from:30038, delay:0.0001s, distance:173.02m (Euclidean)
[2025-03-07 13:59:23,901] [INFO] [30076] Received PREPARE: id:1741323542381, from:30142, delay:0.0002s, distance:266.83m (Euclidean)
[2025-03-07 13:59:23,929] [INFO] [30076] Received COMMIT: id:1741323542381, from:30142, delay:0.0002s, distance:266.83m (Euclidean)
[2025-03-07 13:59:24,169] [INFO] [30076] Received PREPARE: id:1741323542381, from:30152, delay:0.0002s, distance:266.15m (Euclidean)
[2025-03-07 13:59:24,169] [INFO] [30076] Received COMMIT: id:1741323542381, from:30152, delay:0.0002s, distance:266.15m (Euclidean)
[2025-03-07 13:59:24,181] [INFO] [30076] Received COMMIT: id:1741323542381, from:30044, delay:0.0000s, distance:249.29m (Euclidean)
[2025-03-07 13:59:24,283] [INFO] [30076] Received COMMIT: id:1741323542381, from:30099, delay:0.0001s, distance:174.13m (Euclidean)
[2025-03-07 13:59:24,308] [INFO] [30076] Received PREPARE: id:1741323542381, from:30097, delay:0.0000s, distance:150.76m (Euclidean)
[2025-03-07 13:59:24,451] [INFO] [30076] Received PREPARE: id:1741323542381, from:30075, delay:0.0002s, distance:273.64m (Euclidean)
[2025-03-07 13:59:24,451] [INFO] [30076] Received COMMIT: id:1741323542381, from:30075, delay:0.0002s, distance:273.64m (Euclidean)
[2025-03-07 13:59:24,824] [INFO] [30076] Received COMMIT: id:1741323542381, from:30097, delay:0.0000s, distance:150.76m (Euclidean)
[2025-03-07 13:59:24,925] [INFO] [30076] Received PREPARE: id:1741323542381, from:30033, delay:0.0001s, distance:224.34m (Euclidean)
[2025-03-07 13:59:24,925] [INFO] [30076] Received COMMIT: id:1741323542381, from:30033, delay:0.0001s, distance:224.34m (Euclidean)
[2025-03-07 13:59:25,533] [INFO] [30076] Received PREPARE: id:1741323542381, from:30002, delay:0.0000s, distance:31.26m (Euclidean)
[2025-03-07 13:59:26,255] [INFO] [30076] Received COMMIT: id:1741323542381, from:30009, delay:0.0001s, distance:159.71m (Euclidean)
[2025-03-07 13:59:26,462] [INFO] [30076] Received PREPARE: id:1741323542381, from:30151, delay:0.0001s, distance:225.53m (Euclidean)
[2025-03-07 13:59:26,462] [INFO] [30076] Received COMMIT: id:1741323542381, from:30151, delay:0.0001s, distance:225.53m (Euclidean)
[2025-03-07 13:59:26,986] [INFO] [30076] Received PREPARE: id:1741323542381, from:30192, delay:0.0001s, distance:248.22m (Euclidean)
[2025-03-07 13:59:27,706] [INFO] [30076] Received PREPARE: id:1741323542381, from:30078, delay:0.0002s, distance:287.17m (Euclidean)
[2025-03-07 13:59:27,706] [INFO] [30076] Received COMMIT: id:1741323542381, from:30078, delay:0.0002s, distance:287.17m (Euclidean)
[2025-03-07 13:59:27,857] [INFO] [30076] Received COMMIT: id:1741323542381, from:30192, delay:0.0001s, distance:248.22m (Euclidean)
[2025-03-07 13:59:28,086] [INFO] [30076] Received COMMIT: id:1741323542381, from:30002, delay:0.0000s, distance:31.26m (Euclidean)
[2025-03-07 13:59:28,355] [INFO] [30076] Received PREPARE: id:1741323542381, from:30164, delay:0.0002s, distance:271.45m (Euclidean)
[2025-03-07 13:59:28,411] [INFO] [30076] Received COMMIT: id:1741323542381, from:30164, delay:0.0002s, distance:271.45m (Euclidean)
[2025-03-07 13:59:33,279] [INFO] [30076] Received PREPARE: id:1741323542381, from:30172, delay:0.0002s, distance:290.52m (Euclidean)
[2025-03-07 13:59:33,295] [INFO] [30076] Received PREPARE: id:1741323542381, from:30185, delay:0.0001s, distance:214.44m (Euclidean)
[2025-03-07 13:59:33,945] [INFO] [30076] Received COMMIT: id:1741323542381, from:30172, delay:0.0002s, distance:290.52m (Euclidean)
[2025-03-07 13:59:36,482] [INFO] [30076] Received COMMIT: id:1741323542381, from:30185, delay:0.0001s, distance:214.44m (Euclidean)
[2025-03-07 13:59:38,080] [INFO] [30076] Received PREPARE: id:1741323542381, from:30030, delay:0.0001s, distance:208.22m (Euclidean)
[2025-03-07 13:59:38,098] [INFO] [30076] Received PREPARE: id:1741323542381, from:30018, delay:0.0001s, distance:211.53m (Euclidean)
[2025-03-07 13:59:38,098] [INFO] [30076] Received COMMIT: id:1741323542381, from:30018, delay:0.0001s, distance:211.53m (Euclidean)
[2025-03-07 13:59:38,107] [INFO] [30076] Received COMMIT: id:1741323542381, from:30047, delay:0.0002s, distance:295.15m (Euclidean)
[2025-03-07 13:59:38,122] [INFO] [30076] Received COMMIT: id:1741323542381, from:30030, delay:0.0001s, distance:208.22m (Euclidean)
[2025-03-07 13:59:38,190] [INFO] [30076] Received COMMIT: id:1741323542381, from:30082, delay:0.0001s, distance:213.38m (Euclidean)
[2025-03-07 13:59:38,320] [INFO] [30076] Received PREPARE: id:1741323542381, from:30163, delay:0.0001s, distance:205.98m (Euclidean)
[2025-03-07 13:59:38,525] [INFO] [30076] Received PREPARE: id:1741323542381, from:30183, delay:0.0002s, distance:265.24m (Euclidean)
[2025-03-07 13:59:38,531] [INFO] [30076] Received COMMIT: id:1741323542381, from:30183, delay:0.0002s, distance:265.24m (Euclidean)
